# Generated by Django 5.1.15 on 2026-09-29 10:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branch", "0008_merge_0007"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("asset_tag", models.CharField(max_length=50, unique=True)),
                ("asset_name", models.CharField(max_length=150)),
                ("category", models.CharField(max_length=100)),
                ("asset_type", models.CharField(max_length=100)),
                ("brand", models.CharField(blank=True, default="", max_length=100)),
                ("model", models.CharField(blank=True, default="", max_length=100)),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("vendor", models.CharField(blank=True, default="", max_length=150)),
                ("warranty_start_date", models.DateField(blank=True, null=True)),
                ("warranty_end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("assigned", "Assigned"),
                            ("under_repair", "Under Repair"),
                            ("lost", "Lost"),
                            ("damaged", "Damaged"),
                            ("retired", "Retired"),
                            ("disposed", "Disposed"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("damaged", "Damaged"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="branch.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "assets_asset",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssetAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("assigned", "Assigned"), ("returned", "Returned")],
                        default="assigned",
                        max_length=10,
                    ),
                ),
                ("assigned_date", models.DateField()),
                (
                    "condition_at_assignment",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("damaged", "Damaged"),
                        ],
                        max_length=20,
                    ),
                ),
                ("expected_return_date", models.DateField(blank=True, null=True)),
                ("assign_remarks", models.TextField(blank=True, default="")),
                ("return_date", models.DateField(blank=True, null=True)),
                (
                    "return_condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("new", "New"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("damaged", "Damaged"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("return_reason", models.TextField(blank=True, default="")),
                ("return_remarks", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="assets.asset",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "returned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_returns_processed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "assets_assignment",
                "ordering": ["-assigned_date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["status"], name="asset_status_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["branch", "status"], name="asset_branch_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assetassignment",
            index=models.Index(
                fields=["employee", "-assigned_date"], name="assetassign_emp_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assetassignment",
            index=models.Index(
                fields=["asset", "status"], name="assetassign_asset_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="assetassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "assigned")),
                fields=("asset",),
                name="unique_active_assignment_per_asset",
            ),
        ),
    ]
