# Generated by Django 5.1.15 on 2026-09-30 07:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0004_seed_asset_categories_and_types"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetMaintenanceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="in_progress",
                        max_length=15,
                    ),
                ),
                ("maintenance_start_date", models.DateField()),
                ("issue", models.TextField()),
                ("expected_completion_date", models.DateField(blank=True, null=True)),
                ("vendor", models.CharField(blank=True, default="", max_length=150)),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("completed_date", models.DateField(blank=True, null=True)),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("repaired", "Repaired"),
                            ("not_repairable", "Not Repairable"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("maintenance_notes", models.TextField(blank=True, default="")),
                (
                    "actual_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_records",
                        to="assets.asset",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_maintenance_completed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sent_to_maintenance_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_maintenance_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "assets_maintenance_record",
                "ordering": ["-maintenance_start_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["asset", "status"], name="assetmaint_asset_status_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "in_progress")),
                        fields=("asset",),
                        name="unique_active_maintenance_per_asset",
                    )
                ],
            },
        ),
    ]
