# Generated by Django 4.2.16 on 2026-07-01 11:20

import datetime
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("branch", "0005_fix_gps_decimal_precision"),
        ("attendance", "0009_punch_geofencing"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="attendancesettings",
            name="as_active_idx",
        ),
        migrations.AlterField(
            model_name="attendanceabsencealert",
            name="alert_after_days",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="Consecutive absent working days (without approved leave) that trigger the alert.",
            ),
        ),
        migrations.AlterField(
            model_name="attendanceabsencealert",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="attendancecorrection",
            name="requested_in_time",
            field=models.TimeField(
                blank=True,
                help_text="Correct punch-in time. Required when punch_type is IN or BOTH.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="attendancecorrection",
            name="requested_out_time",
            field=models.TimeField(
                blank=True,
                help_text="Correct punch-out time. Required when punch_type is OUT or BOTH.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="attendancelatemarkrules",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="attendancelatemarkrules",
            name="late_marks_per_lop",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="Number of late marks in a calendar month that trigger one LOP deduction. 0 = tracking only — late marks recorded but no LOP applied.",
            ),
        ),
        migrations.AlterField(
            model_name="attendanceovertimerules",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="attendanceovertimerules",
            name="ot_multiplier_holiday",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("2.00"),
                help_text="Pay multiplier for overtime worked on declared holidays.",
                max_digits=3,
            ),
        ),
        migrations.AlterField(
            model_name="attendanceovertimerules",
            name="ot_multiplier_regular",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.50"),
                help_text="Pay multiplier for regular weekday overtime (e.g. 1.5 = time-and-a-half).",
                max_digits=3,
            ),
        ),
        migrations.AlterField(
            model_name="attendanceovertimerules",
            name="ot_threshold_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("9.00"),
                help_text="Total hours worked in a day before overtime begins.",
                max_digits=4,
            ),
        ),
        migrations.AlterField(
            model_name="attendancepunch",
            name="accuracy",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="GPS accuracy reported by the device in metres.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="attendancepunch",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                help_text="Resolved branch at the time of punch.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_punches",
                to="branch.branch",
            ),
        ),
        migrations.AlterField(
            model_name="attendancepunch",
            name="calculated_distance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Haversine distance in metres between employee and branch coordinates.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="attendancepunch",
            name="device_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Persistent device fingerprint or browser fingerprint ID.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="attendancepunch",
            name="device_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp reported by the client device (may differ from server time).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="attendancepunch",
            name="is_inside_geofence",
            field=models.BooleanField(
                help_text="True = inside allowed radius. False = outside. None = geofence not evaluated (branch has no coordinates or WFH mode).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="attendancepunch",
            name="is_regularized",
            field=models.BooleanField(
                default=False,
                help_text="True when added via an approved attendance correction.",
            ),
        ),
        migrations.AlterField(
            model_name="attendancepunch",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Employee GPS latitude at punch time.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="attendancepunch",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Employee GPS longitude at punch time.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="attendancepunch",
            name="punched_at",
            field=models.DateTimeField(
                help_text="Server timestamp of the punch event."
            ),
        ),
        migrations.AlterField(
            model_name="attendancepunchrules",
            name="early_exit_grace_minutes",
            field=models.PositiveSmallIntegerField(
                default=30,
                help_text="Minutes before shift end that an early departure is forgiven.",
            ),
        ),
        migrations.AlterField(
            model_name="attendancepunchrules",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="attendancepunchrules",
            name="min_hours_full_day",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("8.00"),
                help_text="Minimum clocked hours to count as a full present day.",
                max_digits=4,
            ),
        ),
        migrations.AlterField(
            model_name="attendancepunchrules",
            name="min_hours_half_day",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("4.00"),
                help_text="Minimum clocked hours to count as a half-day present.",
                max_digits=4,
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="total_working_minutes",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Net working time in minutes after break deduction.",
            ),
        ),
        migrations.AlterField(
            model_name="attendanceweeklyoff",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="attendanceworkinghours",
            name="break_duration_minutes",
            field=models.PositiveSmallIntegerField(
                default=30, help_text="Break deduction in minutes. 0 = no deduction."
            ),
        ),
        migrations.AlterField(
            model_name="attendanceworkinghours",
            name="grace_period_minutes",
            field=models.PositiveSmallIntegerField(
                default=15,
                help_text="Minutes of late-arrival tolerance before punch is flagged late.",
            ),
        ),
        migrations.AlterField(
            model_name="attendanceworkinghours",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="attendanceworkinghours",
            name="shift_end",
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AlterField(
            model_name="attendanceworkinghours",
            name="shift_start",
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name="overtimepolicy",
            name="approval_type",
            field=models.CharField(
                choices=[
                    ("none", "Not Required"),
                    ("auto", "Auto Approve"),
                    ("manual", "Requires Approval"),
                ],
                default="manual",
                help_text="Whether overtime requires explicit manager/HR approval.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="overtimepolicy",
            name="holiday_overtime_multiplier",
            field=models.DecimalField(
                decimal_places=1,
                default="2.0",
                help_text="Pay multiplier for holiday overtime (e.g. 2.0 = double pay). Min 1.0.",
                max_digits=3,
            ),
        ),
        migrations.AlterField(
            model_name="overtimepolicy",
            name="minimum_overtime_minutes",
            field=models.PositiveSmallIntegerField(
                default=30,
                help_text="Minutes beyond shift end before overtime counting begins. Work within this buffer is not treated as overtime.",
            ),
        ),
        migrations.AlterField(
            model_name="overtimepolicy",
            name="round_off_rule",
            field=models.CharField(
                choices=[
                    ("none", "No Rounding"),
                    ("15_min", "Round to nearest 15 minutes"),
                    ("30_min", "Round to nearest 30 minutes"),
                    ("60_min", "Round to nearest 60 minutes"),
                ],
                default="none",
                help_text="How calculated overtime minutes are rounded before recording.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="overtimepolicy",
            name="weekly_off_overtime_multiplier",
            field=models.DecimalField(
                decimal_places=1,
                default="2.0",
                help_text="Pay multiplier for weekly-off overtime (e.g. 1.5 = time and a half). Min 1.0.",
                max_digits=3,
            ),
        ),
        migrations.AlterField(
            model_name="punchrulespolicy",
            name="auto_checkout_enabled",
            field=models.BooleanField(
                default=False,
                help_text="When True, the system automatically punches out the employee at auto_checkout_time if they have not already punched out.",
            ),
        ),
        migrations.AlterField(
            model_name="punchrulespolicy",
            name="early_checkout_grace",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Minutes before scheduled shift end that an employee can punch out without the departure being flagged as early checkout.",
            ),
        ),
        migrations.AlterField(
            model_name="punchrulespolicy",
            name="max_punch_count",
            field=models.PositiveSmallIntegerField(
                default=2,
                help_text='Maximum punch events per day (each IN or OUT counts as one). Forced to 1 when punch_mode is "single". Min 2 for "multiple".',
            ),
        ),
        migrations.AlterField(
            model_name="punchrulespolicy",
            name="missing_punch_action",
            field=models.CharField(
                choices=[
                    ("mark_absent", "Mark as Absent"),
                    ("mark_half_day", "Mark as Half Day"),
                    ("require_regularization", "Require Regularization"),
                    ("auto_regularize", "Auto Regularize"),
                ],
                default="require_regularization",
                help_text="Action taken when an employee has an IN punch but no OUT punch (or vice versa).",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="punchrulespolicy",
            name="punch_mode",
            field=models.CharField(
                choices=[("single", "Single Punch"), ("multiple", "Multiple Punch")],
                default="multiple",
                help_text="Single: one punch-in required, auto-checkout handles out. Multiple: unlimited in/out pairs up to max_punch_count.",
                max_length=10,
            ),
        ),
    ]
