# Generated by Django 4.2.16 on 2026-07-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0010_fix_gps_decimal_precision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancepunch",
            name="browser",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="attendancepunch",
            name="operating_system",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
