# Generated by Django 4.2.16 on 2026-07-02 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("attendance", "0011_punch_browser_field_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceImportLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("success_rows", models.PositiveIntegerField(default=0)),
                ("failed_rows", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="processing",
                        max_length=15,
                    ),
                ),
                ("errors", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "imported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_imports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "attendance_import_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceOvertime",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("ot_start", models.TimeField()),
                ("ot_end", models.TimeField()),
                ("ot_minutes", models.PositiveIntegerField(default=0)),
                (
                    "ot_type",
                    models.CharField(
                        choices=[
                            ("regular", "Regular (1.5×)"),
                            ("holiday", "Holiday (2.0×)"),
                            ("weekly_off", "Weekly Off (1.5×)"),
                        ],
                        default="regular",
                        max_length=15,
                    ),
                ),
                (
                    "ot_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_overtime",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_overtime",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overtime_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "attendance_overtime",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(fields=["employee", "date"], name="ot_emp_date_idx"),
                    models.Index(fields=["status"], name="ot_status_idx"),
                    models.Index(fields=["date"], name="ot_date_idx"),
                ],
            },
        ),
    ]
