# Generated by Django 4.2.16 on 2026-07-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0013_incomplete_status_and_unpunch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendanceworkinghours",
            name="missing_punch_grace_minutes",
            field=models.PositiveSmallIntegerField(
                default=10,
                help_text="Minutes after shift end before a missing clock-out triggers an un-punch alert. Employee is marked Incomplete and notified after shift_end + this value.",
            ),
        ),
    ]
