# Generated by Django 4.2.16 on 2026-07-03 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("attendance", "0014_alter_attendanceworkinghours_missing_punch_grace_minutes"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvalidPunch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("issue_type", models.CharField(blank=True, default="", max_length=20)),
                ("issue", models.CharField(blank=True, default="", max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("assigned", "Assigned"),
                            ("discarded", "Discarded"),
                            ("converted", "Converted"),
                        ],
                        default="open",
                        max_length=15,
                    ),
                ),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("discarded_at", models.DateTimeField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, default="")),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_invalid_punch_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_invalid_punches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "converted_punch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="converted_from_invalid",
                        to="attendance.attendancepunch",
                    ),
                ),
                (
                    "discarded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discarded_invalid_punches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "punch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invalid_record",
                        to="attendance.attendancepunch",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_invalid_punch_actions",
                "indexes": [
                    models.Index(fields=["punch"], name="invp_punch_idx"),
                    models.Index(fields=["status"], name="invp_status_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AttendanceAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Calendar date of the attendance event (denormalised)."
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("CLOCK_IN", "Clock In"),
                            ("CLOCK_OUT", "Clock Out"),
                            ("PROCESSED", "Attendance Processed"),
                            ("RECALCULATED", "Attendance Recalculated"),
                            ("CORRECTION_SUBMITTED", "Correction Submitted"),
                            ("CORRECTION_APPROVED", "Correction Approved"),
                            ("CORRECTION_REJECTED", "Correction Rejected"),
                            ("MANUALLY_EDITED", "Manually Edited"),
                            ("IMPORTED", "Imported"),
                            ("REPROCESSED", "Reprocessed"),
                            ("INVALID_DISCARDED", "Invalid Punch Discarded"),
                            ("INVALID_CONVERTED", "Invalid Punch Converted"),
                        ],
                        max_length=30,
                    ),
                ),
                ("old_value", models.CharField(blank=True, default="", max_length=200)),
                ("new_value", models.CharField(blank=True, default="", max_length=200)),
                ("action", models.CharField(blank=True, default="", max_length=300)),
                ("remarks", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        blank=True,
                        help_text="The attendance record this event belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="attendance.attendancerecord",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_audit_logs",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["record", "created_at"], name="audit_rec_time_idx"
                    ),
                    models.Index(
                        fields=["employee", "date"], name="audit_emp_date_idx"
                    ),
                    models.Index(fields=["event"], name="audit_event_idx"),
                ],
            },
        ),
    ]
