# Generated by Django 4.2.16 on 2026-07-23 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0016_attendance_import_log_task_id"),
        ("attendance", "0016_seed_missing_clockout_email_template"),
    ]

    operations = []
