# Generated by Django 4.2.16 on 2026-07-23 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("attendance", "0017_merge_20260723_1558"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancecorrection",
            name="l1_actioned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancecorrection",
            name="l1_approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="l1_attendance_corrections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attendancecorrection",
            name="l1_remarks",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="attendancecorrection",
            name="l1_status",
            field=models.CharField(
                blank=True,
                choices=[("approved", "Approved"), ("rejected", "Rejected")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="attendancecorrection",
            name="l2_actioned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancecorrection",
            name="l2_approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="l2_attendance_corrections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attendancecorrection",
            name="l2_remarks",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="attendancecorrection",
            name="l2_status",
            field=models.CharField(
                blank=True,
                choices=[("approved", "Approved"), ("rejected", "Rejected")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="attendancecorrection",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("l2_pending", "L2 Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
