# Generated by Django 4.2.16 on 2026-07-24 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_merge_20260723_1644'),
        ('attendance', '0018_attendancecorrection_l1_actioned_at_and_more'),
    ]

    operations = [
    ]
