# Generated by Django 6.0.7 on 2026-08-03 06:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0019_merge_20260724_1251"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeWeeklyOffAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("effective_from", models.DateField()),
                (
                    "effective_to",
                    models.DateField(
                        blank=True,
                        help_text="Null means this assignment is currently open (in effect until superseded).",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_weekly_off_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_off_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        help_text="PROTECT — a policy actively assigned to an employee cannot be deleted out from under them.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_assignments",
                        to="attendance.weeklydaypolicy",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_weekly_off_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "attendance_employee_weekly_off_assignment",
                "ordering": ["-effective_from"],
                "indexes": [
                    models.Index(
                        fields=["employee", "effective_from"], name="ewoa_emp_from_idx"
                    ),
                    models.Index(
                        fields=["employee", "effective_to"], name="ewoa_emp_to_idx"
                    ),
                ],
            },
        ),
    ]
