# Generated by Django 6.0.7 on 2026-08-03 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0020_employeeweeklyoffassignment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="attendancecorrection",
            index=models.Index(fields=["status"], name="corr_status_idx"),
        ),
    ]
