# Generated by Django 6.0.7 on 2026-08-04 00:00

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0021_phase4_index_review"),
        ("branch", "0008_merge_0007"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FaceRegistrationRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("face_embedding", models.JSONField()),
                ("embedding_model_version", models.CharField(default="face-api.js-faceRecognitionNet-v1", max_length=50)),
                ("liveness_passed", models.BooleanField(default=False)),
                ("liveness_score", models.FloatField(blank=True, null=True)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")], db_index=True, default="pending", max_length=20)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="face_registrations_approved", to=settings.AUTH_USER_MODEL)),
                ("branch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="face_registration_requests", to="branch.branch")),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="face_registration_requests", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "attendance_face_registration_request",
                "ordering": ["-created_at"],
            },
        ),
    ]
