# Generated by Django 4.2.16 on 2026-08-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_seed_face_registration_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepunch',
            name='face_match_distance',
            field=models.FloatField(blank=True, help_text='Euclidean distance between submitted and registered face descriptors. Null when face verification did not apply.', null=True),
        ),
        migrations.AddField(
            model_name='attendancepunch',
            name='face_verified',
            field=models.BooleanField(default=False, help_text='True only when the employee has an approved face registration and their submitted face matched it at punch time.'),
        ),
        migrations.AlterField(
            model_name='attendancepunch',
            name='source',
            field=models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('biometric', 'Biometric'), ('manual', 'Manual'), ('system', 'System'), ('voice', 'Voice Command')], default='web', max_length=10),
        ),
    ]
