# Generated by Django 4.2.16 on 2026-08-05 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0024_attendance_punch_face_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceFaceVerificationRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mandatory', models.BooleanField(default=False, help_text='When on, face ID registration is mandatory for every employee and is enforced at web clock-in/out.')),
                ('settings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_verification', to='attendance.attendancesettings')),
            ],
            options={
                'db_table': 'attendance_settings_face_verification',
            },
        ),
    ]
