# Generated by Django 4.2.16 on 2026-08-06 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0026_seed_face_verification_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceVerificationAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('web', 'Web'), ('voice', 'Voice Command')], help_text='Which clock-in channel produced this attempt.', max_length=10)),
                ('capture_session_id', models.CharField(blank=True, default='', help_text='Client-generated UUID for the camera session this capture came from.', max_length=64)),
                ('embedding_fingerprint', models.CharField(help_text='SHA-256 hex digest of the submitted embedding — never the raw vector.', max_length=64)),
                ('liveness_passed', models.BooleanField(default=False)),
                ('liveness_score', models.FloatField(blank=True, null=True)),
                ('is_match', models.BooleanField(default=False)),
                ('distance', models.FloatField(blank=True, help_text='Euclidean distance to the approved registration. Null when rejected before a distance could be computed (e.g. blocked by the cap).', null=True)),
                ('rejection_reason', models.CharField(blank=True, choices=[('', 'Matched'), ('mismatch', 'Face Mismatch'), ('replay_detected', 'Replay Detected'), ('attempt_cap_exceeded', 'Attempt Cap Exceeded'), ('insecure_transport', 'Insecure Transport')], default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_verification_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attendance_face_verification_attempt',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'created_at'], name='fva_emp_time_idx'), models.Index(fields=['employee', 'is_match', 'created_at'], name='fva_emp_match_time_idx'), models.Index(fields=['embedding_fingerprint', 'created_at'], name='fva_fingerprint_time_idx')],
            },
        ),
    ]
