# Generated by Django 4.2.16 on 2026-08-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0030_fix_weekly_off_assignment_fk_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceregistrationrequest',
            name='consent_given_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faceregistrationrequest',
            name='consent_text_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
