# Generated by Django 5.2 on 2026-08-12 07:43
#
# Depends on 0031_face_registration_consent (merged in from demo, adding
# consent_given_at/consent_text_version) rather than 0030 directly — both
# migrations add disjoint fields to the same model off the same base, which
# would otherwise leave two leaf migrations in this app and force a merge
# migration on the next makemigrations run. Repointed here to linearize
# the history instead: 0030 -> 0031 -> 0032.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0031_face_registration_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceregistrationrequest',
            name='capture_frame_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faceregistrationrequest',
            name='capture_variance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
