# Generated by Django 5.2 on 2026-08-13 08:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0032_face_registration_capture_quality'),
        ('branch', '0008_merge_0007'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='faceregistrationrequest',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='faceregistrationrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('employee',), name='uniq_active_face_registration_per_employee'),
        ),
    ]
