# Generated by Django 5.2 on 2026-08-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0034_backfill_face_registration_active_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceverificationattempt',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('', 'Matched'), ('mismatch', 'Face Mismatch'), ('replay_detected', 'Replay Detected'), ('attempt_cap_exceeded', 'Attempt Cap Exceeded'), ('insecure_transport', 'Insecure Transport'), ('low_confidence_pending', 'Low-Confidence Match Pending Confirmation')], default='', max_length=30),
        ),
    ]
