# Generated by Django 5.2 on 2026-08-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0035_face_verification_low_confidence_rejection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceverificationattempt',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('', 'Matched'), ('mismatch', 'Face Mismatch'), ('replay_detected', 'Replay Detected'), ('attempt_cap_exceeded', 'Attempt Cap Exceeded'), ('insecure_transport', 'Insecure Transport'), ('low_confidence_pending', 'Low-Confidence Match Rejected')], default='', max_length=30),
        ),
    ]
