# Generated by Django 4.2.16 on 2026-08-14 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0032_fix_face_registration_request_is_active_default"),
        ("attendance", "0036_face_verification_fail_closed_low_confidence"),
    ]

    operations = []
