# Generated by Django 4.2.16 on 2026-08-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0037_merge_20260814_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceverificationattempt',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('', 'Matched'), ('mismatch', 'Face Mismatch'), ('replay_detected', 'Replay Detected'), ('attempt_cap_exceeded', 'Attempt Cap Exceeded'), ('insecure_transport', 'Insecure Transport'), ('low_confidence_pending', 'Low-Confidence Match Rejected'), ('liveness_failed', 'Liveness Check Failed')], default='', max_length=30),
        ),
    ]
