# Generated by Django 4.2.16 on 2026-08-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0039_alter_faceregistrationrequest_face_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='work_mode',
            field=models.CharField(choices=[('office', 'Office'), ('wfh', 'Work From Home')], default='office', max_length=10),
        ),
    ]
