# Generated by Django 5.1.15 on 2026-08-25 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0040_attendancerecord_work_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='faceverificationattempt',
            index=models.Index(fields=['employee', 'embedding_fingerprint', 'created_at'], name='fva_emp_fingerprint_time_idx'),
        ),
    ]
