# Generated by Django 5.1.15 on 2026-08-25 12:08
# Renumbered from the ai branch's 0041_faceverificationattempt_fva_emp_
# fingerprint_time_idx.py — that number collided with this session's own
# 0041_seed_regularization_email_templates.py (also a direct child of
# 0040_attendancerecord_work_mode). Re-pointed at 0042 to keep one linear
# chain instead of requiring a separate Django merge migration. Operations
# are otherwise unchanged from the original.

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0042_seed_face_registration_email_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='faceverificationattempt',
            index=models.Index(fields=['employee', 'embedding_fingerprint', 'created_at'], name='fva_emp_fingerprint_time_idx'),
        ),
    ]
