# Generated by Django 5.1.15 on 2026-10-07 10:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0043_faceverificationattempt_fva_emp_fingerprint_time_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeShiftAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("effective_from", models.DateField()),
                (
                    "effective_to",
                    models.DateField(
                        blank=True,
                        help_text="Null means this assignment is currently open (in effect until superseded).",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_shift_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        help_text="PROTECT — a shift actively assigned to an employee cannot be deleted out from under them.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_assignments",
                        to="attendance.workinghourspolicy",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_shift_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "attendance_employee_shift_assignment",
                "ordering": ["-effective_from"],
                "indexes": [
                    models.Index(
                        fields=["employee", "effective_from"], name="esa_emp_from_idx"
                    ),
                    models.Index(
                        fields=["employee", "effective_to"], name="esa_emp_to_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("effective_to__isnull", True)),
                        fields=("employee",),
                        name="uniq_open_shift_assignment_per_employee",
                    )
                ],
            },
        ),
    ]
