# Generated by Django 5.1.15 on 2026-10-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0046_facecapturetelemetry"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancepunch",
            name="location_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Reverse-geocoded \"City, State, Country\" (or finer, when available) for this punch's own latitude/longitude — never the employee's assigned branch. Resolved by a best-effort background task after the punch is already saved (see apps.attendance.tasks.reverse_geocode_punch_task); empty when not yet resolved or when geocoding failed.",
                max_length=255,
            ),
        ),
    ]
