# Generated by Django 4.2.16 on 2026-07-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branch", "0004_branch_geofencing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="geofencing_enabled",
            field=models.BooleanField(
                default=False,
                help_text="When True, employees must be within allowed_radius_meters of the branch coordinates to record an office punch. Requires latitude + longitude to be set.",
            ),
        ),
    ]
