# Generated by Django 4.2.16 on 2026-07-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branch", "0005_fix_gps_decimal_precision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Office GPS latitude. Required when geofencing_enabled is True.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="branch",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Office GPS longitude. Required when geofencing_enabled is True.",
                max_digits=12,
                null=True,
            ),
        ),
    ]
