# Generated by Django 4.2.16 on 2026-07-03 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("branch", "0007_employee_branch_access"),
        ("branch", "0007_merge_branch"),
    ]

    operations = []
