# Generated by Django 5.1.15 on 2026-08-26 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0096_remove_company_gstin_company_bank_account_holder_and_more"),
        ("branch", "0008_merge_0007"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="gst_registration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branches",
                to="accounts.companygstregistration",
            ),
        ),
    ]
