# Generated by Django 5.1.15 on 2026-09-09 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("branch", "0009_branch_gst_registration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branch",
            name="employees_count",
        ),
    ]
