# Generated by Django 5.1.15 on 2026-09-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branch", "0010_remove_branch_employees_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="is_metro",
            field=models.BooleanField(default=False),
        ),
    ]
