# Generated by Django 6.0.4 on 2026-10-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branch", "0011_branch_is_metro"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="attributes",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
