from apps.dashboard.views.birthday_widgets import MyBirthdayWidgetsView
from apps.dashboard.views.manager import ManagerDashboardView
from apps.dashboard.views.overview import (
    SystemAdminKPIView,
    SystemAdminAnnouncementView,
    SystemAdminPendingApprovalsView,
    SystemAdminDepartmentHeadcountView,
    HRDepartmentHeadcountView,
    HRKPIView,
    HRActionQueueView,
    HRRecruitmentFunnelView,
    HRAttendanceSummaryView,
    SharedAnnouncementView,
    EmployeeKPIView,
    EmployeeLeaveBalanceView,
    EmployeeAttendanceSummaryView,
    EmployeeAttendanceStatusView,
)
from apps.dashboard.views.people import (
    SystemAdminEmployeeLifecycleView,
    SystemAdminBirthdayTodayView,
    SystemAdminBirthdayUpcomingView,
    SystemAdminAuditLogsView,
    HREmployeeLifecycleView,
    HRBirthdayTodayView,
    HRBirthdayUpcomingView,
    EmployeeBirthdayTodayView,
    EmployeeActionItemsView,
    EmployeeRecentRequestsView,
)
__all__ = [
    'MyBirthdayWidgetsView',
    'ManagerDashboardView',
    'SystemAdminKPIView',
    'SystemAdminAnnouncementView',
    'SystemAdminPendingApprovalsView',
    'SystemAdminDepartmentHeadcountView',
    'HRDepartmentHeadcountView',
    'HRKPIView',
    'HRActionQueueView',
    'HRRecruitmentFunnelView',
    'HRAttendanceSummaryView',
    'SharedAnnouncementView',
    'EmployeeKPIView',
    'EmployeeLeaveBalanceView',
    'EmployeeAttendanceSummaryView',
    'EmployeeAttendanceStatusView',
    'SystemAdminEmployeeLifecycleView',
    'SystemAdminBirthdayTodayView',
    'SystemAdminBirthdayUpcomingView',
    'SystemAdminAuditLogsView',
    'HREmployeeLifecycleView',
    'HRBirthdayTodayView',
    'HRBirthdayUpcomingView',
    'EmployeeBirthdayTodayView',
    'EmployeeActionItemsView',
    'EmployeeRecentRequestsView',
]
