# Generated by Django 5.2 on 2026-08-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_phase4_index_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="module",
            field=models.CharField(
                choices=[
                    ("leave", "Leave"),
                    ("attendance", "Attendance"),
                    ("regularization", "Regularization"),
                    ("permission", "Permission"),
                    ("holiday", "Holiday"),
                    ("announcement", "Announcement"),
                    ("birthday", "Birthday"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("leave_applied", "Leave Applied"),
                    ("leave_manager_approved", "Leave Approved by Manager"),
                    ("leave_manager_rejected", "Leave Rejected by Manager"),
                    ("leave_hr_approved", "Leave Approved by HR"),
                    ("leave_hr_rejected", "Leave Rejected by HR"),
                    ("leave_cancelled", "Leave Cancelled"),
                    ("attendance", "Attendance"),
                    ("regularization", "Regularization"),
                    ("permission", "Permission"),
                    ("holiday", "Holiday"),
                    ("announcement", "Announcement"),
                    ("birthday", "Birthday"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
