# Generated by Django 4.2.16 on 2026-08-13 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_add_security_alert_choices"),
        ("notifications", "0004_alter_notification_module_and_more"),
    ]

    operations = []
