# Generated by Django 4.2.16 on 2026-08-18 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notificationsettings'),
        ('notifications', '0006_alter_notification_module_and_more'),
    ]

    operations = [
    ]
