# Generated by Django 5.1.15 on 2026-08-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0007_merge_20260818_1158"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="module",
            field=models.CharField(
                choices=[
                    ("leave", "Leave"),
                    ("attendance", "Attendance"),
                    ("regularization", "Regularization"),
                    ("permission", "Permission"),
                    ("holiday", "Holiday"),
                    ("announcement", "Announcement"),
                    ("birthday", "Birthday"),
                    ("promotion", "Promotion"),
                    ("security", "Security"),
                    ("expense", "Expense"),
                    ("separation", "Separation"),
                    ("documents", "Documents"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("leave_applied", "Leave Applied"),
                    ("leave_manager_approved", "Leave Approved by Manager"),
                    ("leave_manager_rejected", "Leave Rejected by Manager"),
                    ("leave_hr_approved", "Leave Approved by HR"),
                    ("leave_hr_rejected", "Leave Rejected by HR"),
                    ("leave_cancelled", "Leave Cancelled"),
                    ("attendance", "Attendance"),
                    ("regularization", "Regularization"),
                    ("permission", "Permission"),
                    ("holiday", "Holiday"),
                    ("announcement", "Announcement"),
                    ("birthday", "Birthday"),
                    ("promotion", "Promotion"),
                    ("security_alert", "Security Alert"),
                    ("expense_submitted", "Expense Submitted"),
                    ("expense_status", "Expense Status Update"),
                    ("separation_submitted", "Separation Request Submitted"),
                    ("separation_status", "Separation Status Update"),
                    ("document_uploaded", "Document Uploaded"),
                    ("password_reset", "Password Reset"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
