# Generated by Django 4.2.16 on 2026-07-20 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branch', '0008_merge_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePayslip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('annual_ctc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_ctc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('basic', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('special_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_earnings', models.JSONField(blank=True, default=dict, help_text='Additional components keyed by component name and amount')),
                ('reimbursements', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gross_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_working_days', models.PositiveSmallIntegerField(default=0)),
                ('lop_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('lop_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pf_employee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pf_employer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('esi_employee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('esi_employer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pt_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lwf_employee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lwf_employer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Employee'), ('acknowledged', 'Acknowledged'), ('queried', 'Query Raised'), ('resolved', 'Query Resolved'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('payslip_pdf', models.FileField(blank=True, null=True, upload_to='payslips/')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('query_deadline', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payroll_employee_payslips',
                'ordering': ['-cycle__cycle_start', 'employee__full_name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cycle_start_day', models.PositiveSmallIntegerField(default=25, help_text='Day of month the pay cycle starts (e.g. 25)')),
                ('cycle_end_day', models.PositiveSmallIntegerField(default=24, help_text='Day of month the pay cycle ends (e.g. 24 of the following month)')),
                ('pay_day', models.PositiveSmallIntegerField(default=30, help_text='Day of month salary is credited')),
                ('approval_levels', models.CharField(choices=[('L1', 'Manager only (L1)'), ('L1_L2', 'Manager + HR (L1 + L2)')], default='L1_L2', max_length=10)),
                ('employee_query_window_hours', models.PositiveSmallIntegerField(default=24, help_text='Hours employees have to raise queries after payslip is sent')),
                ('enable_reimbursements', models.BooleanField(default=True)),
                ('enable_bonuses', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payroll_settings',
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False, help_text='Exactly one structure should be marked as default')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payroll_salary_structures',
            },
        ),
        migrations.CreateModel(
            name='StatutoryConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pt_applicable', models.BooleanField(default=False)),
                ('pt_slabs', models.JSONField(blank=True, default=list)),
                ('esi_applicable', models.BooleanField(default=True)),
                ('esi_wage_ceiling', models.DecimalField(decimal_places=2, default=21000.0, help_text='Monthly gross above this exempts employee from ESI', max_digits=10)),
                ('esi_employee_rate', models.DecimalField(decimal_places=2, default=0.75, help_text='Employee contribution %', max_digits=5)),
                ('esi_employer_rate', models.DecimalField(decimal_places=2, default=3.25, help_text='Employer contribution %', max_digits=5)),
                ('lwf_applicable', models.BooleanField(default=False)),
                ('lwf_employee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('lwf_employer_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('lwf_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('halfyearly', 'Half-yearly'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='statutory_config', to='branch.state')),
            ],
            options={
                'db_table': 'payroll_statutory_config',
            },
        ),
        migrations.CreateModel(
            name='PayslipQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='payroll.employeepayslip')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslip_queries_raised', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslip_queries_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_payslip_queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cycle_start', models.DateField()),
                ('cycle_end', models.DateField()),
                ('pay_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('attendance_pending', 'Awaiting Attendance Approval'), ('attendance_approved', 'Attendance Approved'), ('processing', 'Processing'), ('payslips_generated', 'Payslips Generated'), ('query_window_open', 'Employee Query Window Open'), ('paid', 'Paid'), ('closed', 'Closed')], default='draft', max_length=30)),
                ('attendance_l1_approved_at', models.DateTimeField(blank=True, null=True)),
                ('attendance_l2_approved_at', models.DateTimeField(blank=True, null=True)),
                ('query_window_closes_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_approved_by_l1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_cycles_l1_approved', to=settings.AUTH_USER_MODEL)),
                ('attendance_approved_by_l2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_cycles_l2_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_cycles_created', to=settings.AUTH_USER_MODEL)),
                ('marked_paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_cycles_marked_paid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_cycles',
                'ordering': ['-cycle_start'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalaryConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('annual_ctc', models.DecimalField(decimal_places=2, help_text='Annual CTC in rupees', max_digits=12)),
                ('effective_from', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_configs', to=settings.AUTH_USER_MODEL)),
                ('salary_structure', models.ForeignKey(blank=True, help_text='Leave blank to use branch/company default', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.salarystructure')),
            ],
            options={
                'db_table': 'payroll_employee_salary_config',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.AddField(
            model_name='employeepayslip',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payrollcycle'),
        ),
        migrations.AddField(
            model_name='employeepayslip',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BranchPayrollConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pf_applicable', models.BooleanField(default=True)),
                ('pf_employee_rate', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('pf_employer_rate', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('pf_wage_ceiling', models.DecimalField(decimal_places=2, default=15000.0, help_text='PF is calculated on min(basic, this ceiling)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_config', to='branch.branch')),
                ('salary_structure', models.ForeignKey(blank=True, help_text='Leave blank to use the company default structure', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.salarystructure')),
            ],
            options={
                'db_table': 'payroll_branch_config',
            },
        ),
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('component_type', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction'), ('allowance', 'Allowance')], max_length=20)),
                ('calculation_type', models.CharField(choices=[('percentage_of_ctc', '% of CTC'), ('percentage_of_basic', '% of Basic'), ('fixed', 'Fixed Amount')], max_length=30)),
                ('value', models.DecimalField(decimal_places=4, help_text='Percentage (e.g. 40.00 for 40%) or fixed rupee amount', max_digits=10)),
                ('is_taxable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='payroll.salarystructure')),
            ],
            options={
                'db_table': 'payroll_salary_components',
                'ordering': ['order', 'name'],
                'unique_together': {('structure', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='employeepayslip',
            unique_together={('cycle', 'employee')},
        ),
    ]
