# Generated by Django 4.2.16 on 2026-07-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_employeepayslip_bonus_breakdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepayslip',
            name='bonus_breakdown',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
