# Generated by Django 4.2.16 on 2026-07-22 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0003_alter_employeepayslip_bonus_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollcycle',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payrollcycle',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollcycle',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_cycles_cancelled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payrollcycle',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('attendance_pending', 'Awaiting Attendance Approval'), ('attendance_approved', 'Attendance Approved'), ('processing', 'Processing'), ('payslips_generated', 'Payslips Generated'), ('query_window_open', 'Employee Query Window Open'), ('paid', 'Paid'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=30),
        ),
    ]
