# Generated by Django 4.2.16 on 2026-07-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_payrollcycle_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='edli_rate',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='EDLI contribution % on wages up to edli_wage_ceiling', max_digits=5),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='edli_wage_ceiling',
            field=models.DecimalField(decimal_places=2, default=15000.0, help_text='Monthly wage ceiling for EDLI computation', max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='epf_admin_rate',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='EPF administrative / inspection charges %', max_digits=5),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='eps_rate',
            field=models.DecimalField(decimal_places=2, default=8.33, help_text='Employer EPS contribution % (EPFO-mandated; update when law changes)', max_digits=5),
        ),
    ]
