# Generated by Django 6.0.7 on 2026-08-03 12:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branch", "0008_merge_0007"),
        ("payroll", "0009_seed_payroll_email_templates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="payrollcycle",
            index=models.Index(fields=["status"], name="cycle_status_idx"),
        ),
        migrations.AddIndex(
            model_name="payrollcycle",
            index=models.Index(
                fields=["cycle_start", "cycle_end"], name="cycle_start_end_idx"
            ),
        ),
    ]
