# Generated by Django 4.2.16 on 2026-08-05 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_phase4_index_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepayslip',
            name='salary_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslips', to='payroll.salarystructure'),
        ),
    ]
