# Generated by Django 4.2.16 on 2026-08-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_employeepayslip_salary_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerattendanceapproval',
            name='self_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollcycle',
            name='hr_self_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
