# Generated by Django 6.0.7 on 2026-08-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0012_managerattendanceapproval_self_approved_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="statutoryconfig",
            name="lwf_due_months",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Calendar months (1-12) in which the configured LWF amount is actually deducted. Ignored when lwf_frequency=monthly (charged every cycle). Required: exactly 1 month for annual, exactly 2 distinct months for halfyearly. Interpreted against the payroll cycle's start-month (same convention PayrollAdjustment.month already uses). Left empty for annual/halfyearly means LWF is not charged until configured.",
            ),
        ),
    ]
