# Generated by Django 4.2.16 on 2026-08-13 09:37

import core.encrypted_fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payroll", "0012_managerattendanceapproval_self_approved_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryTransferBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Confirmation"),
                            ("confirmed", "Confirmed — Locked for Transfer"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("file_generated_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="salary_transfer_batches_cancelled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="salary_transfer_batches_confirmed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cycle",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="salary_transfer_batch",
                        to="payroll.payrollcycle",
                    ),
                ),
                (
                    "file_generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="salary_transfer_batches_downloaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payroll_salary_transfer_batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalaryTransferItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("account_holder_name", models.CharField(max_length=150)),
                (
                    "account_number",
                    core.encrypted_fields.EncryptedCharField(max_length=255),
                ),
                ("ifsc_code", core.encrypted_fields.EncryptedCharField(max_length=255)),
                ("bank_name", models.CharField(blank=True, max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="payroll.salarytransferbatch",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="salary_transfer_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payslip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_items",
                        to="payroll.employeepayslip",
                    ),
                ),
            ],
            options={
                "db_table": "payroll_salary_transfer_items",
                "ordering": ["employee__full_name"],
                "unique_together": {("batch", "payslip")},
            },
        ),
    ]
