# Generated by Django 4.2.16 on 2026-08-13 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0013_salary_transfer_batch"),
        ("payroll", "0013_statutoryconfig_lwf_due_months"),
    ]

    operations = []
