# Generated by Django 4.2.16 on 2026-08-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0014_merge_20260813_1548"),
    ]

    operations = [
        migrations.AddField(
            model_name="branchpayrollconfig",
            name="pf_wage_basis",
            field=models.CharField(
                choices=[
                    ("basic_only", "Basic salary only (legacy default)"),
                    (
                        "basic_plus_allowances",
                        "Basic + all allowances except HRA (2019 EPFO ruling)",
                    ),
                ],
                default="basic_only",
                help_text="'basic_only' matches this branch's existing behavior (PF wages = basic salary alone). The Supreme Court's 2019 ruling on EPF wages (and Razorpay's documented PF calculation) treats all allowances except HRA as PF wages — select 'basic_plus_allowances' to opt into that stricter, more compliant basis. Defaults to the legacy behavior so existing branches are not silently recalculated; change this explicitly per branch after confirming with your compliance team.",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="employeepayslip",
            name="pf_wage_base",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="branchpayrollconfig",
            name="pf_wage_ceiling",
            field=models.DecimalField(
                decimal_places=2,
                default=15000.0,
                help_text="PF is calculated on min(pf_wage_basis amount, this ceiling)",
                max_digits=10,
            ),
        ),
    ]
