# Generated by Django 5.1.15 on 2026-09-10 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0145_seed_address_line2_field_configs"),
        ("payroll", "0016_branchpayrollconfig_pf_wage_basis_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeesalaryconfig",
            name="linked_promotion",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific promotion (if any) this CTC revision was for",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="salary_revisions",
                to="accounts.promotionrecord",
            ),
        ),
        migrations.AddField(
            model_name="employeesalaryconfig",
            name="reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("promotion", "Promotion"),
                    ("increment", "Annual Increment"),
                    ("market_correction", "Market Correction"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
