# Generated by Django 5.1.15 on 2026-08-31 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0016_branchpayrollconfig_pf_wage_basis_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollsettings",
            name="default_working_days_per_month",
            field=models.PositiveSmallIntegerField(
                default=26,
                help_text="Fallback working-days-in-month used for an employee's payslip calculation when no attendance records exist for the cycle yet.",
            ),
        ),
        migrations.AddField(
            model_name="statutoryconfig",
            name="esi_daily_wage_exemption_threshold",
            field=models.DecimalField(
                decimal_places=2,
                default=176.0,
                help_text="An employee averaging at or below this daily wage is exempt from their own ESI contribution — the employer share is still due regardless. Government-notified threshold (currently ₹176/day); kept configurable here rather than fixed in code in case it changes.",
                max_digits=8,
            ),
        ),
    ]
