# Generated by Django 5.1.15 on 2026-09-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0017_add_ctc_reason_and_promotion_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeesalaryconfig",
            name="reason_note",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
