# Generated by Django 5.1.15 on 2026-09-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0018_add_ctc_reason_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salarycomponent",
            name="calculation_type",
            field=models.CharField(
                choices=[
                    ("percentage_of_ctc", "% of CTC"),
                    ("percentage_of_basic", "% of Basic"),
                    ("fixed", "Fixed Amount"),
                    ("metro_hra_of_basic", "Metro HRA (50%/40% of Basic)"),
                ],
                max_length=30,
            ),
        ),
    ]
