# Generated by Django 5.1.15 on 2026-09-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0021_seed_tax_declarations_approve_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollsettings",
            name="gratuity_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=4.81,
                help_text="Employer gratuity provision % of Basic+DA (standard formula: 15/26/12)",
                max_digits=5,
            ),
        ),
    ]
