# Generated by Django 6.0.4 on 2026-09-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0022_payrollsettings_gratuity_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeepayslip",
            name="income_tax",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
