# Generated by Django 4.2.16 on 2026-07-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0006_alter_expense_status_alter_leaverequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="expense_number",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, unique=True
            ),
        ),
    ]
