# Generated by Django 4.2.16 on 2026-07-22 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0013_expense_disbursed_in_payslip'),
        ('hrms', '0014_seed_leave_email_templates'),
    ]

    operations = [
    ]
