# Generated by Django 4.2.16 on 2026-07-23 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0014_carry_forward"),
        ("hrms", "0015_merge_20260722_1100"),
    ]

    operations = []
