# Generated by Django 6.0.7 on 2026-08-03 12:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0017_seed_expense_email_templates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["employee", "status", "start_date", "end_date"],
                name="leave_emp_status_dates_idx",
            ),
        ),
    ]
