# Generated by Django 5.2 on 2026-08-11 09:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0019_backfill_missing_leave_balances'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeparationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('separation_type', models.CharField(choices=[('resignation', 'Resignation'), ('termination', 'Termination'), ('retirement', 'Retirement'), ('absconding', 'Absconding'), ('contract_end', 'End of Contract'), ('other', 'Other')], max_length=20)),
                ('reason', models.CharField(choices=[('better_opportunity', 'Better Opportunity'), ('higher_studies', 'Higher Studies'), ('relocation', 'Relocation'), ('health_issues', 'Health Issues'), ('family_reasons', 'Family Reasons'), ('career_growth', 'Career Growth'), ('compensation', 'Compensation & Benefits'), ('work_environment', 'Work Environment'), ('performance', 'Performance'), ('misconduct', 'Misconduct'), ('retirement', 'Retirement'), ('other', 'Other')], max_length=30)),
                ('request_date', models.DateField()),
                ('proposed_last_working_day', models.DateField()),
                ('notice_period_days', models.PositiveIntegerField(default=30)),
                ('comments', models.TextField(blank=True, default='')),
                ('document', models.FileField(blank=True, null=True, upload_to='separation_documents/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('approver_remarks', models.TextField(blank=True, default='')),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='separation_approvals', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='separation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hrms_separation_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
