# Generated by Django 5.2 on 2026-08-11 10:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0020_separationrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='separationrequest',
            name='actioned_at',
        ),
        migrations.RemoveField(
            model_name='separationrequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='separationrequest',
            name='approver_remarks',
        ),
        migrations.AddField(
            model_name='separationrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='separation_requests_filed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='separationrequest',
            name='request_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='separationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('stage2_pending', 'Stage 2 Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='SeparationActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='separation_activities', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='hrms.separationrequest')),
            ],
            options={
                'db_table': 'hrms_separation_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeparationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('resignation_letter', 'Resignation Letter'), ('relieving_letter', 'Relieving Letter'), ('experience_letter', 'Experience Letter'), ('full_final_statement', 'Full & Final Statement'), ('nda', 'NDA / Undertaking'), ('other', 'Other')], default='other', max_length=30)),
                ('file', models.FileField(upload_to='separation_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hrms.separationrequest')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='separation_documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hrms_separation_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeparationHandoverTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='separation_handover_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='separation_handover_tasks_created', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handover_tasks', to='hrms.separationrequest')),
            ],
            options={
                'db_table': 'hrms_separation_handover_tasks',
                'ordering': ['is_completed', 'due_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeparationApprovalStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('hr', 'HR Approval'), ('manager', 'Manager Approval'), ('branch_admin', 'Branch Admin Approval')], max_length=20)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='separation_approval_stages', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_stages', to='hrms.separationrequest')),
            ],
            options={
                'db_table': 'hrms_separation_approval_stages',
                'ordering': ['request', 'sequence'],
                'unique_together': {('request', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='SeparationClearance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clearance_type', models.CharField(choices=[('manager', 'Manager Clearance'), ('it', 'IT Clearance'), ('finance', 'Finance Clearance'), ('hr', 'HR Clearance')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='separation_clearances_given', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearances', to='hrms.separationrequest')),
            ],
            options={
                'db_table': 'hrms_separation_clearances',
                'ordering': ['clearance_type'],
                'unique_together': {('request', 'clearance_type')},
            },
        ),
    ]
