# Generated by Django 5.2 on 2026-08-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0021_remove_separationrequest_actioned_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='separationrequest',
            name='reason',
            field=models.CharField(choices=[('better_career_opportunity', 'Better Career Opportunity'), ('personal_reason', 'Personal Reason'), ('higher_education', 'Higher Education'), ('relocation', 'Relocation'), ('compensation', 'Compensation'), ('health_family', 'Health / Family'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='separationrequest',
            name='separation_type',
            field=models.CharField(choices=[('resignation', 'Resignation'), ('retirement', 'Retirement'), ('other', 'Other')], max_length=20),
        ),
    ]
