# Generated by Django 4.2.16 on 2026-08-19 10:36

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0022_alter_separationrequest_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensereceipt',
            name='file',
            field=models.FileField(storage=core.storage.AuthenticatedRawMediaCloudinaryStorage(), upload_to=core.storage.expense_receipt_upload_path),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='document',
            field=models.FileField(blank=True, null=True, storage=core.storage.AuthenticatedRawMediaCloudinaryStorage(), upload_to=core.storage.leave_document_upload_path),
        ),
        migrations.AlterField(
            model_name='separationdocument',
            name='file',
            field=models.FileField(storage=core.storage.AuthenticatedRawMediaCloudinaryStorage(), upload_to=core.storage.separation_document_upload_path),
        ),
        migrations.AlterField(
            model_name='separationrequest',
            name='document',
            field=models.FileField(blank=True, null=True, storage=core.storage.AuthenticatedRawMediaCloudinaryStorage(), upload_to=core.storage.separation_request_upload_path),
        ),
    ]
