# Generated by Django 4.2.16 on 2026-08-22 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrms', '0023_alter_expensereceipt_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkFromHomeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True, default='')),
                ('location_label', models.CharField(blank=True, default='', max_length=150)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('l2_pending', 'L2 Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('l1_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20, null=True)),
                ('l1_remarks', models.TextField(blank=True, default='')),
                ('l1_actioned_at', models.DateTimeField(blank=True, null=True)),
                ('l2_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20, null=True)),
                ('l2_remarks', models.TextField(blank=True, default='')),
                ('l2_actioned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wfh_requests', to=settings.AUTH_USER_MODEL)),
                ('l1_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='l1_wfh_approvals', to=settings.AUTH_USER_MODEL)),
                ('l2_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='l2_wfh_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hrms_wfh_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'status', 'start_date', 'end_date'], name='wfh_emp_status_dates_idx')],
            },
        ),
    ]
