# Generated by Django 4.2.16 on 2026-08-23 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrms', '0024_workfromhomerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='WFHSavedLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wfh_saved_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hrms_wfh_saved_locations',
                'ordering': ['label'],
                'unique_together': {('employee', 'label')},
            },
        ),
    ]
