# Generated by Django 5.1.15 on 2026-09-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0026_seed_separation_email_templates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="separationrequest",
            name="separation_type",
            field=models.CharField(
                choices=[
                    ("resignation", "Resignation"),
                    ("retirement", "Retirement"),
                    ("termination", "Termination"),
                    ("layoff", "Layoff / Redundancy"),
                    ("end_of_contract", "End of Contract"),
                    ("absconding", "Absconding"),
                    ("death", "Death"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
