# Generated by Django 5.1.15 on 2026-09-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0027_alter_separationrequest_separation_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="separationrequest",
            name="reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("better_career_opportunity", "Better Career Opportunity"),
                    ("personal_reason", "Personal Reason"),
                    ("higher_education", "Higher Education"),
                    ("relocation", "Relocation"),
                    ("compensation", "Compensation"),
                    ("health_family", "Health / Family"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
