# Generated by Django 5.1.15 on 2026-09-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0028_separation_reason_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="separationrequest",
            name="reason_note",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
