# Generated by Django 5.1.15 on 2026-09-10 10:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0029_separation_reason_note"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SeparationSettlement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pro_rata_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "leave_encashment_days",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                (
                    "leave_encashment_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("notice_period_required_days", models.PositiveIntegerField(default=0)),
                ("notice_period_served_days", models.PositiveIntegerField(default=0)),
                (
                    "notice_period_shortfall_days",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "notice_period_recovery_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "gratuity_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "statutory_bonus_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "reimbursements_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "advances_recovery_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "tds_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "other_adjustment_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("other_adjustment_note", models.CharField(blank=True, max_length=200)),
                (
                    "net_payable_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("finalized", "Finalized")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "finalized_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="separation_settlements_finalized",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlement",
                        to="hrms.separationrequest",
                    ),
                ),
            ],
            options={
                "db_table": "hrms_separation_settlements",
            },
        ),
    ]
