# Generated by Django 5.1.15 on 2026-09-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0030_separation_settlement"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavebalance",
            name="last_monthly_accrual",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leavepolicy",
            name="accrual_frequency",
            field=models.CharField(
                choices=[
                    ("annual", "Annual (lump sum on Jan 1)"),
                    ("monthly", "Monthly (1/12th credited each month)"),
                ],
                default="annual",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="leavebalance",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("casual", "Casual Leave"),
                    ("earned", "Earned Leave"),
                    ("sick", "Sick Leave"),
                    ("lwp", "Leave Without Pay"),
                    ("maternity", "Maternity Leave"),
                    ("paternity", "Paternity Leave"),
                    ("bereavement", "Bereavement Leave"),
                    ("comp_off", "Compensatory Off"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("casual", "Casual Leave"),
                    ("earned", "Earned Leave"),
                    ("sick", "Sick Leave"),
                    ("lwp", "Leave Without Pay"),
                    ("maternity", "Maternity Leave"),
                    ("paternity", "Paternity Leave"),
                    ("bereavement", "Bereavement Leave"),
                    ("comp_off", "Compensatory Off"),
                ],
                max_length=20,
            ),
        ),
    ]
