# Generated by Django 5.1.15 on 2026-09-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0033_seed_hr_help_respond_permission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hrhelprequest",
            name="topic",
            field=models.CharField(
                choices=[
                    ("payroll_query", "Payroll query"),
                    ("leave_query", "Leave query"),
                    ("attendance_query", "Attendance query"),
                    ("document_request", "Document request"),
                    ("policy_question", "Policy question"),
                    ("asset_request", "Asset request"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
