# Generated by Django 4.2.16 on 2026-07-23 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0043_company_financial_year"),
        ("accounts", "0043_seed_payroll_view_own_permission"),
    ]

    operations = []
