# Generated by Django 4.2.16 on 2026-07-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0044_merge_20260723_1558"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalworkflowrule",
            name="workflow_type",
            field=models.CharField(
                choices=[
                    ("leave", "Leave Request"),
                    ("expense", "Expense Claim"),
                    ("resignation", "Resignation"),
                    ("loan", "Loan Request"),
                    ("attendance_correction", "Attendance Correction"),
                ],
                max_length=25,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="employeeapprovaloverride",
            name="workflow_type",
            field=models.CharField(
                choices=[
                    ("leave", "Leave Request"),
                    ("expense", "Expense Claim"),
                    ("resignation", "Resignation"),
                    ("loan", "Loan Request"),
                    ("attendance_correction", "Attendance Correction"),
                ],
                max_length=25,
            ),
        ),
    ]
