# Generated by Django 4.2.16 on 2026-07-24 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_alter_approvalworkflowrule_workflow_type_and_more'),
        ('accounts', '0045_remove_payroll_view_from_manager'),
    ]

    operations = [
    ]
