# Generated by Django 4.2.16 on 2026-07-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_merge_20260724_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_manage_team',
            field=models.BooleanField(default=False, help_text='Users with this role appear in manager dropdowns and can manage a team.'),
        ),
    ]
