# Generated by Django 6.0.7 on 2026-08-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0047_role_add_can_manage_team"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["module", "created_at"], name="auditlog_module_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["branch", "is_active"], name="user_branch_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["onboarding_status", "is_active"],
                name="user_onboard_active_idx",
            ),
        ),
    ]
