# Generated by Django 4.2.16 on 2026-07-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_role_add_can_manage_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='name_as_per_aadhar',
            field=models.CharField(blank=True, help_text='Name exactly as printed on the Aadhaar card', max_length=150),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='uan_number',
            field=models.CharField(blank=True, help_text='12-digit Universal Account Number issued by EPFO', max_length=12),
        ),
    ]
