# Generated by Django 4.2.16 on 2026-08-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0048_alter_employeedocument_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="can_manage_branch",
            field=models.BooleanField(
                default=False,
                help_text="Users with this role have unconditional access to every employee, request, and record within their own branch — not limited to employees specifically assigned to them (unlike HR) or their direct reports (unlike a manager). Scoped to one branch, unlike settings.edit which is org-wide.",
            ),
        ),
    ]
