# Generated by Django 4.2.16 on 2026-08-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0048_add_uan_aadhar_to_employee_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeedocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("pan_card", "PAN Card"),
                    ("aadhaar_card", "Aadhaar Card"),
                    ("degree_certificate", "Degree Certificate"),
                    ("experience_letter", "Experience Letter"),
                    ("passport_photo", "Passport Photo"),
                    ("cancelled_cheque", "Cancelled Cheque"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
