# Generated by Django 4.2.16 on 2026-08-05 09:49

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0055_widen_employee_document_file_name_column"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeedocument",
            name="file",
            field=models.FileField(
                max_length=255, upload_to=apps.accounts.models._employee_doc_path
            ),
        ),
    ]
