# Generated by Django 4.2.16 on 2026-08-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0061_backfill_onboarding_approved_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="pan_number",
            field=models.CharField(
                blank=True,
                help_text="10-character PAN (e.g. ABCDE1234F) — unique per person, PII requiring encryption at rest.",
                max_length=10,
            ),
        ),
    ]
