# Generated by Django 5.2 on 2026-08-07 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0061_backfill_onboarding_approved_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="BirthdaySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "banner_message_template",
                    models.TextField(
                        default="We wish you a wonderful year filled with happiness, good health, success, and prosperity. Have an amazing birthday! 🎂"
                    ),
                ),
                (
                    "employee_notification_template",
                    models.TextField(
                        default="We wish you a wonderful birthday and a successful year ahead."
                    ),
                ),
                (
                    "team_notification_template",
                    models.TextField(
                        default="Today is {employee_name}'s birthday. Take a moment to wish your teammate a wonderful birthday."
                    ),
                ),
                (
                    "manager_notification_template",
                    models.TextField(
                        default="Today is {employee_name}'s birthday. Your team member is celebrating their birthday today."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="birthday_settings_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hrms_birthday_settings",
            },
        ),
    ]
