# Generated by Django 4.2.16 on 2026-08-12 12:31

from django.db import migrations, models


def backfill_branch_from_actor(apps, schema_editor):
    """
    Best-effort backfill for existing rows: use the acting user's branch.
    This doesn't recover the true target branch for historical rows where
    an admin acted on another branch's data, but it matches exactly what
    the audit view already showed for these rows before this migration, so
    it's not a regression — only new rows going forward get the more
    accurate target-branch value at the call sites that pass one explicitly.
    """
    AuditLog = apps.get_model('accounts', 'AuditLog')
    rows = list(
        AuditLog.objects.filter(user__isnull=False)
        .exclude(user__branch='')
        .select_related('user')
        .only('id', 'user__branch')
    )
    for row in rows:
        row.branch = row.user.branch
    AuditLog.objects.bulk_update(rows, ['branch'], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0062_employeeprofile_pan_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="branch",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.RunPython(backfill_branch_from_actor, migrations.RunPython.noop),
    ]
