# Generated by Django 4.2.16 on 2026-08-12 12:31
#
# The database_operations side of the AddField below is guarded with an
# IF NOT EXISTS check rather than running unconditionally: on environments
# that already carry the `hrms_audit_logs.branch` drift (production, and
# other branches' independent fixes for the same drift merged around the
# same time — see 0065_auditlog_branch_state_sync, 0065_fix_audit_log_branch_not_null),
# an unconditional ALTER TABLE ADD COLUMN would fail with DuplicateColumn.
# On a genuinely fresh install with none of that history, this is what
# actually creates the column for real.

from django.db import migrations, models


def backfill_branch_from_actor(apps, schema_editor):
    """
    Best-effort backfill for existing rows: use the acting user's branch.
    This doesn't recover the true target branch for historical rows where
    an admin acted on another branch's data, but it matches exactly what
    the audit view already showed for these rows before this migration, so
    it's not a regression — only new rows going forward get the more
    accurate target-branch value at the call sites that pass one explicitly.
    """
    AuditLog = apps.get_model('accounts', 'AuditLog')
    rows = list(
        AuditLog.objects.filter(user__isnull=False)
        .exclude(user__branch='')
        .select_related('user')
        .only('id', 'user__branch')
    )
    for row in rows:
        row.branch = row.user.branch
    AuditLog.objects.bulk_update(rows, ['branch'], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0062_employeeprofile_pan_number"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="auditlog",
                    name="branch",
                    field=models.CharField(blank=True, default="", max_length=100),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            IF NOT EXISTS (
                                SELECT 1 FROM information_schema.columns
                                WHERE table_name = 'hrms_audit_logs' AND column_name = 'branch'
                            ) THEN
                                ALTER TABLE hrms_audit_logs ADD COLUMN branch varchar(100) NOT NULL DEFAULT '';
                            END IF;
                        END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.RunPython(backfill_branch_from_actor, migrations.RunPython.noop),
    ]
