# Generated by Django 5.2 on 2026-08-11 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0062_birthdaysettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="reporting_approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approver_for",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
