# Generated by Django 4.2.16 on 2026-08-12 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_seed_separation_approve_permission'),
        ('accounts', '0063_user_reporting_approver'),
    ]

    operations = [
    ]
