# Generated by Django 4.2.16 on 2026-08-13 09:27

import core.encrypted_fields
from django.db import migrations, models


def encrypt_existing_pii(apps, schema_editor):
    """
    One-pass, idempotent backfill: reassigning each encrypted field to its
    own current value re-saves it through EncryptedCharField.get_prep_value,
    encrypting legacy plaintext for the first time. Rows already encrypted
    (e.g. if this migration is re-run) are simply decrypted then
    re-encrypted with a fresh IV — same plaintext, harmless churn, not data
    loss. pan_number_hash is computed here explicitly because the historical
    model used inside a migration doesn't carry EmployeeProfile's real
    save() override.
    """
    from core.encrypted_fields import blind_index

    EmployeeProfile = apps.get_model('accounts', 'EmployeeProfile')
    for profile in EmployeeProfile.objects.all().iterator():
        profile.pan_number_hash = blind_index(profile.pan_number) if profile.pan_number else ''
        profile.save(update_fields=[
            'account_number', 'ifsc_code', 'name_as_per_aadhar',
            'uan_number', 'pan_number', 'pan_number_hash',
        ])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0063_auditlog_add_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="pan_number_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="account_number",
            field=core.encrypted_fields.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="ifsc_code",
            field=core.encrypted_fields.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="name_as_per_aadhar",
            field=core.encrypted_fields.EncryptedCharField(
                blank=True,
                help_text="Name exactly as printed on the Aadhaar card",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="pan_number",
            field=core.encrypted_fields.EncryptedCharField(
                blank=True,
                help_text="10-character PAN (e.g. ABCDE1234F) — unique per person, encrypted at rest.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="uan_number",
            field=core.encrypted_fields.EncryptedCharField(
                blank=True,
                help_text="12-digit Universal Account Number issued by EPFO",
                max_length=255,
            ),
        ),
        migrations.RunPython(encrypt_existing_pii, migrations.RunPython.noop),
    ]
