# Generated by Django 4.2.16 on 2026-08-13 09:45

import core.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0064_encrypt_sensitive_pii"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="esi_number",
            field=core.encrypted_fields.EncryptedCharField(
                blank=True,
                help_text="10-digit ESI Insurance Number (IP Number) issued by ESIC",
                max_length=255,
            ),
        ),
    ]
