# Generated by Django 6.0.7 on 2026-08-12 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0064_merge_20260812_1213"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromotionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_designation", models.CharField(blank=True, max_length=100)),
                ("new_designation", models.CharField(blank=True, max_length=100)),
                ("previous_role", models.CharField(blank=True, max_length=50)),
                ("new_role", models.CharField(blank=True, max_length=50)),
                ("effective_date", models.DateField()),
                ("remarks", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "promoted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotions_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hrms_promotion_records",
                "ordering": ["-effective_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["employee", "-effective_date"],
                        name="promo_employee_effdate_idx",
                    )
                ],
            },
        ),
    ]
