# Generated by Django 6.0.7 on 2026-08-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0065_promotionrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="designation",
            name="level",
            field=models.PositiveIntegerField(
                default=0,
                help_text='Seniority level used to validate promotions (higher = more senior). 0 means "not yet configured" — promotion hierarchy validation is skipped for a designation until it is given a real level > 0.',
            ),
        ),
    ]
