# Generated by Django 4.2.16 on 2026-08-13 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_fix_audit_log_branch_not_null'),
        ('accounts', '0066_designation_level'),
    ]

    operations = [
    ]
