# Generated by Django 4.2.16 on 2026-08-13 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_auditlog_branch_state_sync'),
        ('accounts', '0067_merge_20260813_1306'),
    ]

    operations = [
    ]
