# Generated by Django 4.2.16 on 2026-08-13 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_auditlog_add_branch'),
        ('accounts', '0068_merge_20260813_1316'),
    ]

    operations = [
    ]
