# Generated by Django 4.2.16 on 2026-08-13 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0065_add_esi_number"),
        ("accounts", "0069_merge_20260813_1331"),
    ]

    operations = []
