# Generated by Django 4.2.16 on 2026-08-14 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0070_merge_0065_add_esi_number_0069_merge_20260813_1331"),
        ("accounts", "0070_revoke_settings_edit_from_branch_admin"),
    ]

    operations = []
