# Generated by Django 4.2.16 on 2026-08-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0073_remove_seeded_demo_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="branch",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
