# Generated by Django 4.2.16 on 2026-08-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0074_alter_auditlog_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="brand_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Hex accent color (e.g. "#1e4e8c") applied to this company\'s own login page and dashboard. Blank uses the default.',
                max_length=7,
            ),
        ),
    ]
