# Generated by Django 4.2.16 on 2026-08-20 12:29

from django.db import migrations, models

# Role names have already drifted from the original seed in some schemas
# (see migration 0043's note: 'hr_admin' -> 'hr') and there's no dedicated
# boolean flag for "this is the HR role" or "this is the employee role" the
# way there is for branch_admin/manager — so those two are matched by every
# name variant seen in this codebase's history. system_admin and branch_admin
# and manager are matched by their actual capability flags instead of name,
# so this keeps working even if a company renames them later.
_HR_NAME_VARIANTS       = {'hr', 'hr_admin'}
_EMPLOYEE_NAME_VARIANTS = {'employee'}


def mark_system_roles(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    db_alias = schema_editor.connection.alias

    qs = Role.objects.using(db_alias)
    # settings.edit is this codebase's own "sees/does everything" signal
    # (see core/permissions.py has_perm) — whichever role(s) carry it are
    # this company's system-admin-equivalent tier.
    qs.filter(role_permissions__permission__codename='settings.edit').update(is_system_role=True)
    qs.filter(can_manage_branch=True).update(is_system_role=True)
    qs.filter(can_manage_team=True).update(is_system_role=True)
    qs.filter(name__in=_HR_NAME_VARIANTS).update(is_system_role=True)
    qs.filter(name__in=_EMPLOYEE_NAME_VARIANTS).update(is_system_role=True)


def unmark_system_roles(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    Role.objects.using(schema_editor.connection.alias).update(is_system_role=False)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0075_company_brand_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="is_system_role",
            field=models.BooleanField(
                default=False,
                help_text="One of the roles this company was provisioned with (System Admin, Branch Admin, HR, Manager, Employee) — cannot be deleted, regardless of name. Permissions and the display name stay fully editable; only deletion is blocked, so the rest of the app can always assume these roles exist.",
            ),
        ),
        migrations.RunPython(mark_system_roles, unmark_system_roles),
    ]
