# Generated by Django 4.2.16 on 2026-08-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0075_company_brand_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingFieldConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=150)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Long text'), ('number', 'Number'), ('date', 'Date'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox')], default='text', max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('step', models.PositiveSmallIntegerField(choices=[(0, 'Personal Information'), (1, 'Education & Experience'), (2, 'Bank Details'), (3, 'Emergency Contact')])),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('required', models.BooleanField(default=False)),
                ('is_custom', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hrms_onboarding_field_configs',
                'ordering': ['step', 'order'],
            },
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='custom_field_values',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
