# Generated by Django 4.2.16 on 2026-08-19 10:46

import apps.accounts.models
import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0078_fix_onboarding_field_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='file',
            field=models.FileField(max_length=255, storage=core.storage.AuthenticatedRawMediaCloudinaryStorage(), upload_to=apps.accounts.models._employee_doc_path),
        ),
    ]
