# Generated by Django 4.2.16 on 2026-08-19 10:57

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0079_alter_employeedocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=core.storage.AuthenticatedRawMediaCloudinaryStorage(), upload_to=core.storage.document_center_upload_path),
        ),
    ]
