# Generated by Django 4.2.16 on 2026-08-19 11:25

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0080_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.storage.company_logo_upload_path),
        ),
        migrations.AlterField(
            model_name='emailtemplateattachment',
            name='file',
            field=models.FileField(storage=core.storage.AuthenticatedRawMediaCloudinaryStorage(), upload_to=core.storage.email_template_attachment_upload_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.storage.profile_photo_upload_path),
        ),
    ]
