# Generated by Django 4.2.16 on 2026-08-20 10:54

import apps.accounts.models
import core.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0081_alter_company_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingfieldconfig',
            name='allow_multiple',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='onboardingfieldconfig',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Long text'), ('number', 'Number'), ('date', 'Date'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox'), ('file', 'File / Image')], default='text', max_length=20),
        ),
        migrations.CreateModel(
            name='CustomFieldFileValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=64)),
                ('file', models.FileField(max_length=255, storage=core.storage.AuthenticatedRawMediaCloudinaryStorage(), upload_to=apps.accounts.models._custom_field_file_path)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hrms_custom_field_file_values',
                'ordering': ['field_key', '-uploaded_at'],
            },
        ),
    ]
