# Generated by Django 4.2.16 on 2026-08-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0082_onboardingfieldconfig_allow_multiple_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTypeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_key', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=150)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('required', models.BooleanField(default=False)),
                ('allow_multiple', models.BooleanField(default=False)),
                ('is_custom', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hrms_document_type_configs',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='document_type',
            field=models.CharField(max_length=64),
        ),
    ]
