# Generated by Django 4.2.16 on 2026-08-20 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0077_revoke_settings_edit_from_hr'),
        ('accounts', '0084_seed_document_type_configs'),
    ]

    operations = [
    ]
