# Generated by Django 4.2.16 on 2026-08-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0086_seed_org_chart_view_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalworkflowrule',
            name='workflow_type',
            field=models.CharField(choices=[('leave', 'Leave Request'), ('expense', 'Expense Claim'), ('attendance_correction', 'Attendance Correction'), ('wfh', 'Work From Home Request')], max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='employeeapprovaloverride',
            name='workflow_type',
            field=models.CharField(choices=[('leave', 'Leave Request'), ('expense', 'Expense Claim'), ('attendance_correction', 'Attendance Correction'), ('wfh', 'Work From Home Request')], max_length=25),
        ),
    ]
