# Generated by Django 4.2.16 on 2026-08-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0088_seed_wfh_permissions_and_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecodesettings',
            name='prefix',
            field=models.CharField(default='EMP', max_length=10),
        ),
    ]
