# Generated by Django 4.2.16 on 2026-08-23 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0090_fix_manager_role_can_manage_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='brand_color',
        ),
    ]
