# Generated by Django 5.1.15 on 2026-08-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0094_add_facial_recognition_approve'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'created_at'], name='auditlog_user_created_idx'),
        ),
    ]
