# Generated by Django 5.1.15 on 2026-08-26 06:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0095_fix_hardcoded_company_name_in_email_templates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="gstin",
        ),
        migrations.AddField(
            model_name="company",
            name="bank_account_holder",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="company",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="company",
            name="bank_account_type",
            field=models.CharField(
                blank=True,
                choices=[("savings", "Savings"), ("current", "Current")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="bank_ifsc",
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name="company",
            name="country_of_registration",
            field=models.CharField(
                blank=True,
                choices=[
                    ("US", "United States"),
                    ("GB", "United Kingdom"),
                    ("AE", "United Arab Emirates"),
                    ("SG", "Singapore"),
                    ("AU", "Australia"),
                    ("CA", "Canada"),
                    ("DE", "Germany"),
                    ("FR", "France"),
                    ("NL", "Netherlands"),
                    ("other", "Other"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="date_format",
            field=models.CharField(
                choices=[
                    ("DD-MM-YYYY", "DD-MM-YYYY (31-03-2026)"),
                    ("MM-DD-YYYY", "MM-DD-YYYY (03-31-2026)"),
                    ("YYYY-MM-DD", "YYYY-MM-DD (2026-03-31)"),
                    ("DD/MM/YYYY", "DD/MM/YYYY (31/03/2026)"),
                ],
                default="DD-MM-YYYY",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="date_of_incorporation",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="default_currency",
            field=models.CharField(
                choices=[
                    ("INR", "INR — Indian Rupee (₹)"),
                    ("USD", "USD — US Dollar ($)"),
                    ("EUR", "EUR — Euro (€)"),
                    ("GBP", "GBP — British Pound (£)"),
                    ("AED", "AED — UAE Dirham"),
                    ("SGD", "SGD — Singapore Dollar"),
                    ("AUD", "AUD — Australian Dollar"),
                    ("CAD", "CAD — Canadian Dollar"),
                    ("JPY", "JPY — Japanese Yen"),
                    ("CNY", "CNY — Chinese Yuan"),
                ],
                default="INR",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="ein",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="company",
            name="entity_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("private_limited", "Private Limited — Pvt Ltd"),
                    ("public_limited", "Public Limited — Ltd"),
                    ("llp", "Limited Liability Partnership — LLP"),
                    ("partnership", "Partnership Firm"),
                    ("sole_proprietorship", "Sole Proprietorship"),
                    ("opc", "One Person Company — OPC"),
                    ("corporation", "Corporation (Inc.) — Body corporate"),
                    ("llc", "Limited Liability Company — LLC"),
                    ("foreign_partnership", "Partnership"),
                    ("branch_office", "Branch Office"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="epfo_code",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="company",
            name="esic_code",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="company",
            name="holding_company_info",
            field=models.CharField(
                blank=True,
                help_text="Parent company name and CIN, if this is a subsidiary.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="iec",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="company",
            name="industry",
            field=models.CharField(
                blank=True,
                choices=[
                    ("it_services", "Information Technology & Services"),
                    ("manufacturing", "Manufacturing"),
                    ("healthcare", "Healthcare"),
                    ("finance", "Financial Services"),
                    ("retail", "Retail & E-commerce"),
                    ("education", "Education"),
                    ("construction", "Construction & Real Estate"),
                    ("hospitality", "Hospitality & Travel"),
                    ("logistics", "Logistics & Transportation"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="is_listed",
            field=models.BooleanField(
                default=False,
                help_text="Whether shares are publicly listed on a stock exchange.",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="jurisdiction",
            field=models.CharField(
                choices=[("india", "India"), ("foreign", "Foreign (outside India)")],
                default="india",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="msme_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("micro", "Micro"),
                    ("small", "Small"),
                    ("medium", "Medium"),
                    ("not_registered", "Not registered"),
                ],
                default="not_registered",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="nature_of_business",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="company",
            name="nic_code",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="company",
            name="primary_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="company",
            name="professional_tax_reg",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="company",
            name="registration_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="company",
            name="roc_jurisdiction",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="company",
            name="signatory_appears_on_invoices",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="company",
            name="signatory_designation",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="company",
            name="signatory_din_pan",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="company",
            name="signatory_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="company",
            name="signatory_full_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="company",
            name="timezone",
            field=models.CharField(
                choices=[
                    ("Asia/Kolkata", "Asia/Kolkata — IST (UTC+5:30)"),
                    ("Asia/Dubai", "Asia/Dubai — GST (UTC+4:00)"),
                    ("Asia/Singapore", "Asia/Singapore — SGT (UTC+8:00)"),
                    ("Europe/London", "Europe/London — GMT/BST"),
                    ("America/New_York", "America/New_York — ET"),
                    ("America/Chicago", "America/Chicago — CT"),
                    ("America/Los_Angeles", "America/Los_Angeles — PT"),
                    ("Australia/Sydney", "Australia/Sydney — AET"),
                ],
                default="Asia/Kolkata",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="udyam_msme",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="company",
            name="cin",
            field=models.CharField(blank=True, max_length=21),
        ),
        migrations.AlterField(
            model_name="company",
            name="pan",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="company",
            name="pin_code",
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name="company",
            name="state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="company",
            name="tan",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.CreateModel(
            name="CompanyDirector",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("din", models.CharField(max_length=8)),
                ("name", models.CharField(max_length=150)),
                ("designation", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="directors",
                        to="accounts.company",
                    ),
                ),
            ],
            options={
                "db_table": "hrms_company_director",
                "ordering": ["name"],
                "unique_together": {("company", "din")},
            },
        ),
        migrations.CreateModel(
            name="CompanyGSTRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("gstin", models.CharField(max_length=15)),
                ("state", models.CharField(max_length=100)),
                (
                    "registration_type",
                    models.CharField(
                        choices=[
                            ("regular", "Regular"),
                            ("composition", "Composition"),
                            ("casual", "Casual"),
                            ("other", "Other"),
                        ],
                        default="regular",
                        max_length=20,
                    ),
                ),
                ("place_of_business", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gst_registrations",
                        to="accounts.company",
                    ),
                ),
            ],
            options={
                "db_table": "hrms_company_gst_registration",
                "ordering": ["state"],
                "unique_together": {("company", "gstin")},
            },
        ),
    ]
