# Generated by Django 5.1.15 on 2026-08-25 12:08
# Renumbered from the ai branch's 0095_auditlog_auditlog_user_created_idx.py —
# that file also depended directly on 0094_add_facial_recognition_approve,
# forking the migration graph against this session's own
# 0095_ensure_facial_recognition_approve_defaults/0096_ensure_assessments_
# permissions_defaults (also children of 0094). Re-pointed at 0096 to keep
# a single linear chain instead of requiring a separate Django merge
# migration. Content/operations unchanged from the original.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0096_ensure_assessments_permissions_defaults'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'created_at'], name='auditlog_user_created_idx'),
        ),
    ]
