# Generated by Django 5.1.15 on 2026-08-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0098_auditlog_user_created_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="communication_address",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="company",
            name="communication_address_same_as_registered",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="company",
            name="communication_city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="company",
            name="communication_pin_code",
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name="company",
            name="communication_state",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
