# Generated by Django 5.1.15 on 2026-08-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0101_seed_org_structure_permissions_and_jobs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="entity_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("private_limited", "Private Limited — Pvt Ltd"),
                    ("public_limited", "Public Limited — Ltd"),
                    ("opc", "One Person Company — OPC"),
                    ("llp", "LLP — Partnership"),
                    ("partnership", "Partnership Firm — Firm"),
                    ("sole_proprietorship", "Proprietorship — Sole owner"),
                    ("huf", "HUF — Family"),
                    ("section8", "Section 8 — Non-profit"),
                    ("trust_society", "Trust / Society — Charitable"),
                    ("corporation", "Corporation (Inc.) — Body corporate"),
                    ("llc", "Limited Liability Company — LLC"),
                    ("foreign_partnership", "Partnership"),
                    ("branch_office", "Branch Office"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
