# Generated by Django 5.1.15 on 2026-08-27 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0102_alter_company_entity_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="designation_synced_from_position",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="position",
            name="holder",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="held_positions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
