# Generated by Django 5.1.15 on 2026-08-27 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0103_user_designation_synced_from_position_and_more"),
        ("branch", "0009_branch_gst_registration"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="positions",
                to="branch.branch",
            ),
        ),
    ]
