# Generated by Django 5.1.15 on 2026-08-27 12:11
# Renumbered from 0106 -> 0107 to run after the data backfill (0106), which
# needs Position.holder to still exist while it copies existing holders into
# real Placement rows.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0106_backfill_placements_from_position_holder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="position",
            name="holder",
        ),
    ]
