# Generated by Django 5.1.15 on 2026-08-27 12:28

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.db import migrations, models

from apps.accounts.migration_utils import (
    PortableExclusionConstraint,
    PostgresOnlyAddConstraint,
    PostgresOnlyRemoveConstraint,
)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0108_seed_org_structure_backdate_permission"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="placement",
            name="placement_effective_to_gte_from",
        ),
        PostgresOnlyRemoveConstraint(
            model_name="placement",
            name="placement_position_no_overlap",
        ),
        PostgresOnlyRemoveConstraint(
            model_name="placement",
            name="placement_employee_no_overlap",
        ),
        migrations.AddConstraint(
            model_name="placement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_to__gte", models.F("effective_from")),
                    _connector="OR",
                ),
                name="placement_effective_to_gte_from",
                violation_error_message="The end date cannot be before the start date.",
            ),
        ),
        PostgresOnlyAddConstraint(
            model_name="placement",
            constraint=PortableExclusionConstraint(
                expressions=[
                    ("position", "="),
                    (
                        models.Func(
                            "effective_from",
                            "effective_to",
                            django.contrib.postgres.fields.ranges.RangeBoundary(
                                inclusive_lower=True, inclusive_upper=True
                            ),
                            function="daterange",
                            output_field=django.contrib.postgres.fields.ranges.DateRangeField(),
                        ),
                        "&&",
                    ),
                ],
                name="placement_position_no_overlap",
                violation_error_message="This position already has an overlapping placement for that date range.",
            ),
        ),
        PostgresOnlyAddConstraint(
            model_name="placement",
            constraint=PortableExclusionConstraint(
                expressions=[
                    ("employee", "="),
                    (
                        models.Func(
                            "effective_from",
                            "effective_to",
                            django.contrib.postgres.fields.ranges.RangeBoundary(
                                inclusive_lower=True, inclusive_upper=True
                            ),
                            function="daterange",
                            output_field=django.contrib.postgres.fields.ranges.DateRangeField(),
                        ),
                        "&&",
                    ),
                ],
                name="placement_employee_no_overlap",
                violation_error_message="This employee already has an overlapping placement for that date range.",
            ),
        ),
    ]
