# Generated by Django 5.1.15 on 2026-08-27 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0109_remove_placement_placement_effective_to_gte_from_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgunit",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="org_units",
                to="accounts.department",
            ),
        ),
    ]
