# Generated by Django 5.1.15 on 2026-08-28 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0110_orgunit_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="department_synced_from_position",
            field=models.BooleanField(default=True),
        ),
    ]
