# Generated by Django 5.1.15 on 2026-08-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0111_user_department_synced_from_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgunit",
            name="is_department_level",
            field=models.BooleanField(default=False),
        ),
    ]
