# Generated by Django 5.1.15 on 2026-08-28 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0114_remove_department_designation_permissions"),
        ("announcements", "0005_remove_announcement_target_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orgunit",
            name="department",
        ),
        # AlterUniqueTogether must run before RemoveField(designation.department)
        # — Django needs the field to still exist to find the DB index to drop.
        migrations.AlterUniqueTogether(
            name="designation",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="designation",
            name="department",
        ),
        migrations.DeleteModel(
            name="Department",
        ),
        migrations.DeleteModel(
            name="Designation",
        ),
    ]
