# Generated by Django 5.1.15 on 2026-09-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0117_cleanup_test_org_units"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companydirector",
            name="din",
            field=models.CharField(max_length=20),
        ),
    ]
