# Generated by Django 5.1.15 on 2026-09-08 06:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0123_encrypt_company_director_din"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recipient_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(blank=True, default="", max_length=500)),
                ("body_html", models.TextField(blank=True, default="")),
                (
                    "template_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("context", models.JSONField(blank=True, default=dict)),
                ("module", models.CharField(blank=True, default="", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "Sent"), ("failed", "Failed")], max_length=10
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("had_attachments", models.BooleanField(default=False)),
                (
                    "attachment_filenames",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("has_sensitive_context", models.BooleanField(default=False)),
                ("is_resend", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resend_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resend_attempts",
                        to="accounts.emaillog",
                    ),
                ),
                (
                    "smtp_settings",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="accounts.smtpsettings",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs_triggered",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hrms_email_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="emaillog_status_created_idx",
                    ),
                    models.Index(
                        fields=["module", "created_at"],
                        name="emaillog_module_created_idx",
                    ),
                ],
            },
        ),
    ]
