# Generated by Django 5.1.15 on 2026-09-08 11:59
#
# SMTPSettings.password holds a real, working credential (a mailbox password
# or a provider API key, e.g. Resend's) — same PII/secrets tier as Company's
# PAN/bank fields encrypted in 0121_encrypt_company_pii.py, left as plain
# CharField until now. No blind-index needed (no exact-match lookup on this
# field anywhere in the app, same reasoning as 0121's Company fields).

import core.encrypted_fields
from django.db import migrations


def encrypt_existing_smtp_passwords(apps, schema_editor):
    """One-pass, idempotent backfill — same convention as
    0121_encrypt_company_pii.py's encrypt_existing_company_pii: reassigning
    each row's password to its own current value re-saves it through
    EncryptedCharField.get_prep_value, encrypting legacy plaintext the first
    time this runs. Re-running just re-encrypts with a fresh IV, not data
    loss — safe to run more than once."""
    SMTPSettings = apps.get_model('accounts', 'SMTPSettings')
    for smtp in SMTPSettings.objects.all().iterator():
        smtp.save(update_fields=['password'])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0127_seed_password_reset_by_admin_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smtpsettings",
            name="password",
            field=core.encrypted_fields.EncryptedCharField(max_length=512),
        ),
        migrations.RunPython(encrypt_existing_smtp_passwords, migrations.RunPython.noop),
    ]
