# Generated by Django 5.1.15 on 2026-09-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0130_seed_address_field_configs"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="permanent_same_as_current",
            field=models.BooleanField(default=False),
        ),
    ]
