# Generated by Django 5.1.15 on 2026-09-09 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0131_employeeprofile_permanent_same_as_current"),
        ("branch", "0010_remove_branch_employees_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="branch_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="branch.branch",
            ),
        ),
    ]
