# Generated by Django 5.1.15 on 2026-09-09 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0133_backfill_user_branch_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="default_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for_positions",
                to="accounts.role",
            ),
        ),
    ]
