# Generated by Django 5.1.15 on 2026-09-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0135_rename_branch_admin_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="reporting_manager_from_org_chart",
            field=models.BooleanField(default=False),
        ),
    ]
