# Generated by Django 5.1.15 on 2026-09-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0136_user_reporting_manager_from_org_chart"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="employee_type",
            field=models.CharField(blank=True, default="Permanent", max_length=50),
        ),
    ]
