# Generated by Django 5.1.15 on 2026-09-09 12:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0137_user_employee_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("step", models.PositiveSmallIntegerField(unique=True)),
                ("label", models.CharField(max_length=100)),
                ("icon", models.CharField(default="ti-folder", max_length=50)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "hrms_onboarding_sections",
                "ordering": ["order", "label"],
            },
        ),
    ]
