# Generated by Django 5.1.15 on 2026-09-10 04:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0139_seed_builtin_onboarding_sections"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkExperienceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("employer_name", models.CharField(max_length=200)),
                ("designation", models.CharField(blank=True, max_length=200)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("reason_for_leaving", models.TextField(blank=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experience_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hrms_work_experience_records",
                "ordering": ["order", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="EducationRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("ssc", "SSC / 10th"),
                            ("intermediate", "Intermediate / 12th"),
                            ("diploma", "Diploma"),
                            ("bachelors", "Bachelor's"),
                            ("masters", "Master's"),
                            ("doctorate", "Doctorate"),
                        ],
                        max_length=20,
                    ),
                ),
                ("institution", models.CharField(blank=True, max_length=200)),
                ("specialization", models.CharField(blank=True, max_length=200)),
                (
                    "year_of_passing",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hrms_education_records",
                "ordering": ["id"],
                "unique_together": {("employee", "level")},
            },
        ),
    ]
