# Generated by Django 5.1.15 on 2026-09-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0140_workexperiencerecord_educationrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="workexperiencerecord",
            name="employment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full_time", "Full-time"),
                    ("part_time", "Part-time"),
                    ("internship", "Internship"),
                    ("contract", "Contract"),
                    ("freelance", "Freelance"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workexperiencerecord",
            name="responsibilities",
            field=models.TextField(blank=True),
        ),
    ]
