# Generated by Django 5.1.15 on 2026-09-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0141_workexperiencerecord_employment_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="educationrecord",
            options={"ordering": ["order", "-end_date"]},
        ),
        migrations.AlterUniqueTogether(
            name="educationrecord",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="educationrecord",
            name="custom_level_label",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="educationrecord",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="educationrecord",
            name="order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="educationrecord",
            name="percentage",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="educationrecord",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="educationrecord",
            name="level",
            field=models.CharField(
                choices=[
                    ("ssc", "SSC / 10th"),
                    ("intermediate", "Intermediate / 12th"),
                    ("diploma", "Diploma"),
                    ("bachelors", "Bachelor's"),
                    ("masters", "Master's"),
                    ("doctorate", "Doctorate"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.RemoveField(
            model_name="educationrecord",
            name="year_of_passing",
        ),
    ]
