# Generated by Django 5.1.15 on 2026-09-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0143_rename_address_line_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="current_address_line2",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="permanent_address_line2",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
