# Generated by Django 5.1.15 on 2026-09-10 10:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0145_seed_address_line2_field_configs"),
    ]

    operations = [
        migrations.CreateModel(
            name="EducationExperienceFieldConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "list_type",
                    models.CharField(
                        choices=[
                            ("education", "Education"),
                            ("experience", "Experience"),
                        ],
                        max_length=20,
                    ),
                ),
                ("field_key", models.CharField(max_length=50)),
                ("label", models.CharField(max_length=100)),
                ("visible", models.BooleanField(default=True)),
                ("required", models.BooleanField(default=False)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "hrms_education_experience_field_configs",
                "ordering": ["list_type", "order"],
                "unique_together": {("list_type", "field_key")},
            },
        ),
    ]
