# Generated by Django 5.1.15 on 2026-09-16 06:20

import core.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0148_seed_employees_view_sensitive_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="aadhaar_number",
            field=core.encrypted_fields.EncryptedCharField(
                blank=True,
                help_text="12-digit Aadhaar number issued by UIDAI",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="disability_certificate_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="disability_percentage",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="disability_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("visual", "Visual"),
                    ("hearing", "Hearing"),
                    ("locomotor", "Locomotor"),
                    ("intellectual", "Intellectual"),
                    ("multiple", "Multiple"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="esi_covered",
            field=models.BooleanField(
                default=False,
                help_text="Whether this employee is covered under ESI — normally auto-eligible below the wage threshold",
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="international_worker_country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="is_disabled",
            field=models.BooleanField(
                default=False, help_text="Specially abled declaration (RPwD Act 2016)"
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="is_international_worker",
            field=models.BooleanField(
                default=False,
                help_text="International Worker declaration (EPF Form 11)",
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="passport_expiry",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="passport_number",
            field=core.encrypted_fields.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="pf_covered",
            field=models.BooleanField(
                default=True,
                help_text="Whether this employee is covered under the Provident Fund scheme",
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="pf_number",
            field=core.encrypted_fields.EncryptedCharField(
                blank=True,
                help_text="EPF member/account ID (distinct from the UAN)",
                max_length=255,
            ),
        ),
    ]
