# Generated by Django 5.1.15 on 2026-09-16 06:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0150_seed_statutory_field_configs"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("laptop", "Laptop"),
                            ("mobile_phone", "Mobile Phone"),
                            ("monitor", "Monitor"),
                            ("headset", "Headset"),
                            ("sim_card", "SIM Card"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tag_number", models.CharField(blank=True, max_length=100)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("good", "Good"),
                            ("refurbished", "Refurbished"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("issued_at", models.DateField(blank=True, null=True)),
                ("returned_at", models.DateField(blank=True, null=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hrms_company_assets",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="FamilyMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("father", "Father"),
                            ("mother", "Mother"),
                            ("spouse", "Spouse"),
                            ("child", "Child"),
                            ("sibling", "Sibling"),
                        ],
                        max_length=10,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("blood_group", models.CharField(blank=True, max_length=5)),
                ("is_dependent", models.BooleanField(default=False)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hrms_family_members",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="EPFNominee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scheme",
                    models.CharField(
                        choices=[
                            ("epf_eps", "EPF + EPS"),
                            ("gratuity", "Gratuity"),
                            ("both", "Both"),
                        ],
                        default="epf_eps",
                        max_length=10,
                    ),
                ),
                ("share_percentage", models.PositiveSmallIntegerField(default=0)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="epf_nominees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "family_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nominations",
                        to="accounts.familymember",
                    ),
                ),
            ],
            options={
                "db_table": "hrms_epf_nominees",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
