# Generated by Django 5.1.15 on 2026-09-16 07:01
#
# Backfills existing employees who have already completed onboarding to
# 'confirmed' — there's no historical record of who was actually still on
# probation when this field was introduced, so "already fully onboarded"
# is the closest available proxy. Anyone still mid-onboarding is left on
# the model's own 'probation' default, which is accurate for them either way.

from django.db import migrations, models


def backfill_confirmed(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(onboarding_status='complete').update(employment_status='confirmed')


def backfill_reverse(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.all().update(employment_status='probation', confirmation_date=None)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0151_family_nominee_asset_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="confirmation_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="employment_status",
            field=models.CharField(
                choices=[("probation", "Probation"), ("confirmed", "Confirmed")],
                default="probation",
                max_length=20,
            ),
        ),
        migrations.RunPython(backfill_confirmed, backfill_reverse),
    ]
