# Generated by Django 5.1.15 on 2026-09-17 06:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0153_seed_employees_confirm_permission"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeCodeSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("Permanent", "Permanent"),
                            ("Contract", "Contract"),
                            ("Freelancer", "Freelancer"),
                            ("Consultant", "Consultant"),
                            ("Part-Time", "Part-Time"),
                            ("Temporary", "Temporary"),
                            ("Intern", "Intern"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("prefix", models.CharField(default="EMP", max_length=10)),
                ("padding", models.PositiveSmallIntegerField(default=5)),
                ("next_sequence", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "hrms_employee_code_series",
                "ordering": ["employment_type"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="dotted_line_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dotted_line_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="notice_period_days",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="probation_period_months",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="work_location",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="user",
            name="work_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("office", "Office"),
                    ("remote", "Remote"),
                    ("hybrid", "Hybrid"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="employee_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Permanent", "Permanent"),
                    ("Contract", "Contract"),
                    ("Freelancer", "Freelancer"),
                    ("Consultant", "Consultant"),
                    ("Part-Time", "Part-Time"),
                    ("Temporary", "Temporary"),
                    ("Intern", "Intern"),
                ],
                default="Permanent",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="HireAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("new_position", "New position"),
                            ("replacement", "Replacement"),
                            ("backfill", "Backfill"),
                            ("business_expansion", "Business expansion"),
                            ("rehire", "Rehire"),
                        ],
                        max_length=30,
                    ),
                ),
                ("effective_from", models.DateField()),
                (
                    "employment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Permanent", "Permanent"),
                            ("Contract", "Contract"),
                            ("Freelancer", "Freelancer"),
                            ("Consultant", "Consultant"),
                            ("Part-Time", "Part-Time"),
                            ("Temporary", "Temporary"),
                            ("Intern", "Intern"),
                        ],
                        max_length=50,
                    ),
                ),
                ("reserved_employee_id", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("completed", "Completed"),
                            ("discarded", "Discarded"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hire_actions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hire_action_origin",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hire_actions",
                        to="accounts.position",
                    ),
                ),
            ],
            options={
                "db_table": "hrms_hire_actions",
                "ordering": ["-created_at"],
            },
        ),
    ]
