# Generated by Django 5.1.15 on 2026-09-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0155_seed_employee_code_series"),
    ]

    operations = [
        migrations.AddField(
            model_name="hireaction",
            name="draft_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
