# Generated by Django 5.1.15 on 2026-09-17 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0156_hireaction_draft_data"),
        ("hrms", "0033_seed_hr_help_respond_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="attendance_scheme",
            field=models.CharField(
                blank=True,
                choices=[
                    ("standard", "Standard"),
                    ("flexible", "Flexible"),
                    ("shift_based", "Shift-based"),
                ],
                default="standard",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="leave_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_employees",
                to="hrms.leavepolicy",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="pay_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("monthly", "Monthly – India"),
                    ("weekly", "Weekly"),
                    ("biweekly", "Bi-Weekly"),
                    ("daily", "Daily Wage"),
                ],
                default="monthly",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bank_transfer", "Bank Transfer – NEFT"),
                    ("cheque", "Cheque"),
                    ("cash", "Cash"),
                ],
                default="bank_transfer",
                max_length=20,
            ),
        ),
    ]
