# Generated by Django 5.1.15 on 2026-09-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0157_user_attendance_scheme_user_leave_plan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="display_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="middle_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="nationality",
            field=models.CharField(blank=True, default="Indian", max_length=100),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="place_of_birth",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="salutation",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
