# Generated by Django 5.1.15 on 2026-09-21 07:42

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0158_employeeprofile_display_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hireaction",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=core.storage.profile_photo_upload_path
            ),
        ),
    ]
