# Generated by Django 5.1.15 on 2026-09-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0159_hireaction_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="personal_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
