# Generated by Django 6.0.4 on 2026-09-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0160_employeeprofile_personal_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="effective_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="version",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
