# Generated by Django 6.0.4 on 2026-09-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0161_document_effective_date_document_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotionrecord",
            name="reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("performance_based", "Performance based"),
                    ("role_change", "Role change"),
                    ("market_correction", "Market correction"),
                    ("restructuring", "Restructuring"),
                    ("team_restructuring", "Team restructuring"),
                    ("manager_change", "Manager change"),
                    ("location_transfer", "Location transfer"),
                    ("department_change", "Department change"),
                    ("other", "Other"),
                ],
                default="",
                max_length=30,
            ),
        ),
    ]
