# Generated by Django 6.0.4 on 2026-09-24 08:06

import apps.accounts.models
import core.storage
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0162_promotionrecord_reason"),
    ]

    operations = [
        migrations.CreateModel(
            name="HireActionDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document_type", models.CharField(max_length=64)),
                (
                    "file",
                    models.FileField(
                        max_length=255,
                        storage=core.storage.AuthenticatedImageKitStorage(),
                        upload_to=apps.accounts.models._hire_action_doc_path,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.PositiveBigIntegerField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hire_action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="accounts.hireaction",
                    ),
                ),
            ],
            options={
                "db_table": "hrms_hire_action_documents",
                "ordering": ["document_type", "-uploaded_at"],
            },
        ),
    ]
