# Generated by Django 6.0.4 on 2026-09-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0164_seed_hire_wizard_document_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="hireactiondocument",
            name="content_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
