# Generated by Django 6.0.4 on 2026-09-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0165_hireactiondocument_content_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="passport_country_of_issue",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="passport_issue_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="passport_place_of_issue",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
