# Generated by Django 6.0.4 on 2026-09-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0167_allow_multiple_certificates"),
    ]

    operations = [
        migrations.AddField(
            model_name="hireactiondocument",
            name="entry_ref",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
