# Generated by Django 6.0.4 on 2026-09-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0168_hireactiondocument_entry_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="certifications",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="core_skills",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
