# Generated by Django 6.0.4 on 2026-09-25 07:34

import core.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0170_fix_required_document_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="bank_change_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="bank_change_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "No pending change"),
                    ("pending", "Pending HR review"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="pending_account_holder_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="pending_account_number",
            field=core.encrypted_fields.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="pending_account_type",
            field=models.CharField(
                blank=True,
                choices=[("savings", "Savings"), ("current", "Current")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="pending_bank_branch_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="pending_bank_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="pending_ifsc_code",
            field=core.encrypted_fields.EncryptedCharField(blank=True, max_length=255),
        ),
    ]
