# Generated by Django 6.0.4 on 2026-09-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0174_revoke_edit_own_profile_from_employee_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="passwordresettoken",
            name="opened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="passwordresettoken",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("reset", "Forgot-password reset"),
                    ("invite", "New-hire account activation invite"),
                ],
                default="reset",
                max_length=10,
            ),
        ),
    ]
