# Generated by Django 6.0.4 on 2026-09-28 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0175_password_reset_token_invite_purpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeedocument",
            name="verification_note",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="employeedocument",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending review"),
                    ("verified", "Verified"),
                    ("needs_correction", "Needs correction"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="employeedocument",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employeedocument",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
