# Generated by Django 6.0.4 on 2026-10-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0178_add_external_api_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgunit",
            name="attributes",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="position",
            name="attributes",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
