# Generated by Django 4.2.16 on 2026-08-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0011_welcome_employee_email_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="interview_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="meeting_link",
            field=models.URLField(
                blank=True,
                help_text="Video call link — shown to the candidate when interview_mode is Video Call.",
                max_length=500,
            ),
        ),
    ]
