# Generated by Django 6.0.4 on 2026-10-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0015_seed_candidate_revision_requested_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="attributes",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
