# Generated by Django 4.2.16 on 2026-07-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0005_candidateassignment_employee_nullable_candidate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assessmentitem",
            name="pass_score",
        ),
        migrations.AddField(
            model_name="assessment",
            name="pass_percentage",
            field=models.PositiveSmallIntegerField(default=70),
        ),
    ]
