# Generated by Django 4.2.16 on 2026-07-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0006_assessment_pass_percentage_remove_item_pass_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateassignment",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
