# Generated by Django 4.2.16 on 2026-07-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0009_assessmentsection_assessmentitem_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessmentsettings",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
