# Generated by Django 6.0.7 on 2026-08-03 12:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0010_alter_assessmentsettings_id"),
        ("recruitment", "0011_welcome_employee_email_template"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="candidateassignment",
            index=models.Index(
                fields=["employee", "status"], name="assign_emp_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="candidateassignment",
            index=models.Index(
                fields=["candidate", "status"], name="assign_cand_status_idx"
            ),
        ),
    ]
