# Generated by Django 5.1.15 on 2026-08-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0011_phase4_index_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateassignment",
            name="deadline_reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text='When the one-time "deadline approaching" reminder email was sent — unset means none has gone out yet for this assignment.',
                null=True,
            ),
        ),
    ]
