# Generated by Django 6.0.7 on 2026-08-03 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0055_phase4_index_review"),
        ("announcements", "0001_initial"),
        ("branch", "0008_merge_0007"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["is_pinned", "created_at"], name="ann_pinned_created_idx"
            ),
        ),
    ]
