# Generated by Django 5.1.15 on 2026-08-28 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0111_user_department_synced_from_position"),
        ("announcements", "0002_phase4_index_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="target_org_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="announcements",
                to="accounts.orgunit",
            ),
        ),
    ]
