# Generated by Django 5.1.15 on 2026-08-28 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0004_backfill_target_org_unit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="announcement",
            name="target_department",
        ),
    ]
