# Generated by Django 6.0.4 on 2026-10-06 07:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0178_add_external_api_key"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=3, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("symbol", models.CharField(blank=True, max_length=10)),
                ("minor_units", models.PositiveSmallIntegerField(default=2)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "currencies",
                "db_table": "platform_currencies",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "enabled",
                    models.BooleanField(default=False, help_text="Global default."),
                ),
                (
                    "rollout_percentage",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Only applies when enabled=True and no override matches.",
                    ),
                ),
                ("is_system", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "platform_feature_flags",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="LookupType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="UPPER_SNAKE, e.g. GENDER", max_length=64, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "module",
                    models.CharField(
                        blank=True,
                        help_text='Which app/domain owns this, e.g. "accounts"',
                        max_length=50,
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="Type itself cannot be deleted (values still can be added if allow_custom_values).",
                    ),
                ),
                ("allow_custom_values", models.BooleanField(default=True)),
                ("is_hierarchical", models.BooleanField(default=False)),
                (
                    "attribute_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON Schema validating LookupValue.attributes for this type.",
                    ),
                ),
            ],
            options={
                "db_table": "platform_lookup_types",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Timezone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "platform_timezones",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("iso2", models.CharField(max_length=2, unique=True)),
                ("iso3", models.CharField(max_length=3, unique=True)),
                ("numeric_code", models.CharField(blank=True, max_length=3)),
                ("name", models.CharField(max_length=150)),
                ("phone_code", models.CharField(blank=True, max_length=10)),
                ("date_format", models.CharField(default="DD/MM/YYYY", max_length=20)),
                ("address_format", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "default_currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="countries",
                        to="platform_core.currency",
                    ),
                ),
                (
                    "default_timezone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="countries",
                        to="platform_core.timezone",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "countries",
                "db_table": "platform_countries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LegalEntity",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("legal_name", models.CharField(max_length=255)),
                ("trade_name", models.CharField(blank=True, max_length=255)),
                ("date_format", models.CharField(default="DD/MM/YYYY", max_length=20)),
                (
                    "financial_year_start_month",
                    models.PositiveSmallIntegerField(default=4),
                ),
                ("entity_type", models.CharField(blank=True, max_length=64)),
                ("industry", models.CharField(blank=True, max_length=64)),
                ("msme_class", models.CharField(blank=True, max_length=64)),
                ("jurisdiction", models.CharField(blank=True, max_length=64)),
                ("date_of_incorporation", models.DateField(blank=True, null=True)),
                ("is_listed", models.BooleanField(default=False)),
                ("holding_company_info", models.TextField(blank=True)),
                ("nature_of_business", models.TextField(blank=True)),
                ("nic_code", models.CharField(blank=True, max_length=20)),
                ("registered_address", models.TextField(blank=True)),
                ("communication_address", models.TextField(blank=True)),
                ("primary_email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("official_phone", models.CharField(blank=True, max_length=20)),
                ("portal_url", models.URLField(blank=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="legal_entity_logos/"
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "base_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_entities",
                        to="platform_core.currency",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_entities",
                        to="platform_core.country",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "timezone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_entities",
                        to="platform_core.timezone",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "legal entities",
                "db_table": "platform_legal_entities",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="FeatureFlagOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField()),
                (
                    "flag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overrides",
                        to="platform_core.featureflag",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="platform_core.legalentity",
                    ),
                ),
            ],
            options={
                "db_table": "platform_feature_flag_overrides",
            },
        ),
        migrations.CreateModel(
            name="EntityBankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account_holder_name", models.CharField(blank=True, max_length=255)),
                ("account_number_encrypted", models.BinaryField(blank=True, null=True)),
                (
                    "account_number_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("ifsc_encrypted", models.BinaryField(blank=True, null=True)),
                ("bank_name", models.CharField(blank=True, max_length=255)),
                ("branch_name", models.CharField(blank=True, max_length=255)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to="platform_core.legalentity",
                    ),
                ),
            ],
            options={
                "db_table": "platform_entity_bank_accounts",
            },
        ),
        migrations.CreateModel(
            name="AuthorisedSignatory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=255)),
                ("designation", models.CharField(blank=True, max_length=150)),
                (
                    "purpose",
                    models.CharField(
                        blank=True,
                        help_text="LookupValue code under SIGNATORY_PURPOSE, e.g. BANKING, STATUTORY.",
                        max_length=64,
                    ),
                ),
                ("din_pan_encrypted", models.BinaryField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signatories",
                        to="platform_core.legalentity",
                    ),
                ),
            ],
            options={
                "db_table": "platform_authorised_signatories",
            },
        ),
        migrations.CreateModel(
            name="NumberSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=100, unique=True)),
                (
                    "entity",
                    models.CharField(
                        help_text='Target object type, e.g. "employee", "leave_request".',
                        max_length=50,
                    ),
                ),
                (
                    "pattern",
                    models.CharField(
                        default="{PREFIX}{SEQ:5}",
                        help_text="Tokens: {PREFIX} {SEQ:n} {YYYY} {YY} {MM} {FY} {ENTITY} {BRANCH}",
                        max_length=200,
                    ),
                ),
                ("prefix", models.CharField(blank=True, max_length=20)),
                ("padding", models.PositiveSmallIntegerField(default=5)),
                ("next_value", models.PositiveIntegerField(default=1)),
                (
                    "reset_period",
                    models.CharField(
                        choices=[
                            ("never", "Never"),
                            ("yearly", "Yearly"),
                            ("financial_year", "Financial year"),
                            ("monthly", "Monthly"),
                        ],
                        default="never",
                        max_length=20,
                    ),
                ),
                ("last_reset_key", models.CharField(blank=True, max_length=20)),
                (
                    "scope_key",
                    models.CharField(
                        blank=True,
                        help_text="e.g. employment_type code — free-form scope discriminator.",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.PositiveSmallIntegerField(default=0)),
                (
                    "legal_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="number_series",
                        to="platform_core.legalentity",
                    ),
                ),
            ],
            options={
                "db_table": "platform_number_series",
                "ordering": ["entity", "scope_key"],
            },
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("app_label", models.CharField(max_length=100)),
                ("model_name", models.CharField(max_length=100)),
                ("object_id", models.CharField(max_length=64)),
                ("field", models.CharField(max_length=64)),
                ("language", models.CharField(max_length=10)),
                ("text", models.TextField()),
            ],
            options={
                "db_table": "platform_translations",
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "app_label",
                            "model_name",
                            "object_id",
                            "field",
                            "language",
                        ),
                        name="uniq_translation_target",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rate", models.DecimalField(decimal_places=8, max_digits=20)),
                ("effective_date", models.DateField()),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "manual", "RBI reference rate"',
                        max_length=100,
                    ),
                ),
                (
                    "from_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rates_from",
                        to="platform_core.currency",
                    ),
                ),
                (
                    "to_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rates_to",
                        to="platform_core.currency",
                    ),
                ),
            ],
            options={
                "db_table": "platform_exchange_rates",
                "ordering": ["-effective_date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("from_currency", "to_currency", "effective_date"),
                        name="uniq_exchange_rate_per_day",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EntityIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("identifier_type", models.CharField(max_length=64)),
                ("value", models.CharField(blank=True, max_length=255)),
                ("value_encrypted", models.BinaryField(blank=True, null=True)),
                (
                    "value_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Blind index for sensitive identifiers — lookup without decrypting.",
                        max_length=64,
                    ),
                ),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identifiers",
                        to="platform_core.legalentity",
                    ),
                ),
            ],
            options={
                "db_table": "platform_entity_identifiers",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("legal_entity", "identifier_type"),
                        name="uniq_active_identifier_per_type",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ChangeHistory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("occurred_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "channel",
                    models.CharField(
                        default="ui",
                        help_text="ui, api_key, system, import, voice, celery",
                        max_length=20,
                    ),
                ),
                ("request_id", models.CharField(blank=True, max_length=64)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("object_id", models.CharField(max_length=64)),
                ("object_repr", models.CharField(blank=True, max_length=200)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("deactivate", "Deactivate"),
                            ("restore", "Restore"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="[{field, old, new}] — sensitive values masked before storage.",
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_history_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="platform_core.legalentity",
                    ),
                ),
            ],
            options={
                "db_table": "platform_change_history",
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id", "occurred_at"],
                        name="pch_object_idx",
                    ),
                    models.Index(fields=["actor", "occurred_at"], name="pch_actor_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="LookupValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="UPPER_SNAKE, immutable once referenced by any record.",
                        max_length=64,
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("attributes", models.JSONField(blank=True, default=dict)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="Seeded value — label editable, code is not, cannot be deleted (only deactivated).",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lookup_values",
                        to="platform_core.country",
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lookup_values",
                        to="platform_core.legalentity",
                    ),
                ),
                (
                    "lookup_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="platform_core.lookuptype",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="platform_core.lookupvalue",
                    ),
                ),
            ],
            options={
                "db_table": "platform_lookup_values",
                "ordering": ["lookup_type", "sort_order", "label"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("lookup_type", "code"),
                        name="uniq_lookup_value_code_per_type",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ModuleToggle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("module", models.CharField(max_length=50)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_toggles",
                        to="platform_core.legalentity",
                    ),
                ),
            ],
            options={
                "db_table": "platform_module_toggles",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("module", "legal_entity"),
                        name="uniq_module_toggle_per_entity",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SeedRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("pack", models.CharField(max_length=100)),
                ("version", models.CharField(max_length=20)),
                ("object_id", models.CharField(max_length=64)),
                (
                    "checksum",
                    models.CharField(
                        help_text="Hash of the seed-pack source row, to detect admin edits vs pack updates.",
                        max_length=64,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "db_table": "platform_seed_records",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pack", "content_type", "object_id"),
                        name="uniq_seed_record_target",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="legalentity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("is_primary",),
                name="uniq_primary_legal_entity",
            ),
        ),
    ]
