# Generated by Django 6.0.4 on 2026-10-06 09:09

import apps.platform_core.models.attachments
import core.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0178_add_external_api_key"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("platform_core", "0002_seed_number_series_from_employee_codes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="lower_snake, immutable once published.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(max_length=150)),
                ("plural_label", models.CharField(blank=True, max_length=150)),
                ("description", models.TextField(blank=True)),
                ("module", models.CharField(blank=True, max_length=50)),
                (
                    "kind",
                    models.CharField(
                        choices=[("core", "Core"), ("custom", "Custom")], max_length=10
                    ),
                ),
                ("app_label", models.CharField(blank=True, max_length=100)),
                ("model_name", models.CharField(blank=True, max_length=100)),
                (
                    "attributes_column",
                    models.CharField(
                        blank=True,
                        help_text="Name of the JSONB column holding custom attribute values for this entity.",
                        max_length=100,
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("has_attachments", models.BooleanField(default=True)),
                ("history_enabled", models.BooleanField(default=True)),
                ("title_template", models.CharField(blank=True, max_length=255)),
                (
                    "owner_field",
                    models.CharField(blank=True, default="owner", max_length=64),
                ),
                ("legal_entity_scoped", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "number_series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="platform_core.numberseries",
                    ),
                ),
                (
                    "parent_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_entities",
                        to="platform_core.entitydefinition",
                    ),
                ),
            ],
            options={
                "db_table": "platform_entity_definitions",
                "ordering": ["module", "label"],
            },
        ),
        migrations.CreateModel(
            name="FieldDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="lower_snake, unique per entity, immutable after publish.",
                        max_length=64,
                    ),
                ),
                ("label", models.CharField(max_length=150)),
                ("help_text", models.CharField(blank=True, max_length=255)),
                ("placeholder", models.CharField(blank=True, max_length=150)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("long_text", "Long text"),
                            ("rich_text", "Rich text"),
                            ("integer", "Integer"),
                            ("decimal", "Decimal"),
                            ("currency_amount", "Currency amount"),
                            ("percentage", "Percentage"),
                            ("boolean", "Boolean"),
                            ("date", "Date"),
                            ("datetime", "Date & time"),
                            ("time", "Time"),
                            ("duration", "Duration"),
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("url", "URL"),
                            ("lookup", "Lookup"),
                            ("reference", "Reference"),
                            ("user_reference", "User reference"),
                            ("file", "File"),
                            ("image", "Image"),
                            ("geo_point", "Geo point"),
                            ("json", "JSON (admin only)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "is_core",
                    models.BooleanField(
                        default=False,
                        help_text="Maps to a real model column — definition is auto-generated and type-locked.",
                    ),
                ),
                ("is_system", models.BooleanField(default=False)),
                ("required", models.BooleanField(default=False)),
                ("default_value", models.JSONField(blank=True, null=True)),
                ("multiple", models.BooleanField(default=False)),
                ("validation", models.JSONField(blank=True, default=dict)),
                ("is_sensitive", models.BooleanField(default=False)),
                ("pii_category", models.CharField(blank=True, max_length=64)),
                ("is_unique", models.BooleanField(default=False)),
                (
                    "unique_scope",
                    models.CharField(
                        choices=[
                            ("global", "Global"),
                            ("legal_entity", "Per legal entity"),
                            ("parent_record", "Per parent record"),
                        ],
                        default="global",
                        max_length=20,
                    ),
                ),
                ("is_searchable", models.BooleanField(default=False)),
                ("is_filterable", models.BooleanField(default=False)),
                ("is_sortable", models.BooleanField(default=False)),
                ("is_exportable", models.BooleanField(default=True)),
                ("is_importable", models.BooleanField(default=True)),
                (
                    "applicability",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"countries": [...], "legal_entities": [...], "employment_types": [...]} — empty = all.',
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="platform_core.entitydefinition",
                    ),
                ),
                (
                    "lookup_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="platform_core.lookuptype",
                    ),
                ),
                (
                    "reference_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="platform_core.entitydefinition",
                    ),
                ),
            ],
            options={
                "db_table": "platform_field_definitions",
                "ordering": ["entity", "order"],
            },
        ),
        migrations.CreateModel(
            name="AttachmentValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.CharField(max_length=64)),
                (
                    "file",
                    models.FileField(
                        max_length=255,
                        storage=core.storage.AuthenticatedImageKitStorage(),
                        upload_to=apps.platform_core.models.attachments._attachment_path,
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("size", models.PositiveBigIntegerField()),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                (
                    "checksum",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 of the file content.",
                        max_length=64,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attachments",
                        to="platform_core.fielddefinition",
                    ),
                ),
            ],
            options={
                "db_table": "platform_attachment_values",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="FieldValueUniqueness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope_key", models.CharField(blank=True, max_length=100)),
                ("value_hash", models.CharField(db_index=True, max_length=64)),
                ("record_id", models.CharField(max_length=64)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="platform_core.entitydefinition",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="platform_core.fielddefinition",
                    ),
                ),
            ],
            options={
                "db_table": "platform_field_value_uniqueness",
            },
        ),
        migrations.CreateModel(
            name="FormLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=100)),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("onboarding", "Onboarding"),
                            ("hire_wizard", "Hire wizard"),
                            ("profile_self", "Profile (self)"),
                            ("profile_hr", "Profile (HR)"),
                            ("employee_detail", "Employee detail"),
                            ("candidate_form", "Candidate form"),
                            ("custom_create", "Custom — create"),
                            ("custom_edit", "Custom — edit"),
                            ("custom_view", "Custom — view"),
                        ],
                        max_length=30,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("employment_type", models.CharField(blank=True, max_length=50)),
                ("priority", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="platform_core.country",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layouts",
                        to="platform_core.entitydefinition",
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="platform_core.legalentity",
                    ),
                ),
            ],
            options={
                "db_table": "platform_form_layouts",
                "ordering": ["entity", "context", "-priority"],
            },
        ),
        migrations.CreateModel(
            name="FormSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=150)),
                ("order", models.PositiveIntegerField(default=0)),
                ("columns", models.PositiveSmallIntegerField(default=1)),
                ("collapsible", models.BooleanField(default=False)),
                ("visible_when", models.JSONField(blank=True, default=dict)),
                (
                    "repeats_for_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="platform_core.entitydefinition",
                    ),
                ),
            ],
            options={
                "db_table": "platform_form_sections",
                "ordering": ["step", "order"],
            },
        ),
        migrations.CreateModel(
            name="FormFieldPlacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("column_span", models.PositiveSmallIntegerField(default=1)),
                ("read_only", models.BooleanField(default=False)),
                ("visible_when", models.JSONField(blank=True, default=dict)),
                ("required_when", models.JSONField(blank=True, default=dict)),
                ("label_override", models.CharField(blank=True, max_length=150)),
                ("help_override", models.CharField(blank=True, max_length=255)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="platform_core.fielddefinition",
                    ),
                ),
                (
                    "restricted_to_roles",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="accounts.role"
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="platform_core.formsection",
                    ),
                ),
            ],
            options={
                "db_table": "platform_form_field_placements",
                "ordering": ["section", "order"],
            },
        ),
        migrations.CreateModel(
            name="FormStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=150)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("order", models.PositiveIntegerField(default=0)),
                ("visible_when", models.JSONField(blank=True, default=dict)),
                (
                    "layout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="platform_core.formlayout",
                    ),
                ),
            ],
            options={
                "db_table": "platform_form_steps",
                "ordering": ["layout", "order"],
            },
        ),
        migrations.AddField(
            model_name="formsection",
            name="step",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="platform_core.formstep",
            ),
        ),
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("upsert", "Upsert"),
                        ],
                        default="create",
                        max_length=10,
                    ),
                ),
                (
                    "key_field",
                    models.CharField(
                        blank=True,
                        help_text="Field code used to match existing records for update/upsert.",
                        max_length=64,
                    ),
                ),
                (
                    "file",
                    models.FileField(max_length=255, upload_to="platform_imports/"),
                ),
                (
                    "mapping",
                    models.JSONField(
                        blank=True, default=dict, help_text="{csv_column: field_code}"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("validating", "Validating"),
                            ("validated", "Validated"),
                            ("committing", "Committing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("rolled_back", "Rolled back"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("valid_rows", models.PositiveIntegerField(default=0)),
                ("invalid_rows", models.PositiveIntegerField(default=0)),
                ("created_count", models.PositiveIntegerField(default=0)),
                ("updated_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                (
                    "error_file",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to="platform_imports/errors/",
                    ),
                ),
                (
                    "progress",
                    models.PositiveSmallIntegerField(default=0, help_text="0-100"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "idempotency_key",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_jobs",
                        to="platform_core.entitydefinition",
                    ),
                ),
            ],
            options={
                "db_table": "platform_import_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ListViewDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=150)),
                ("columns", models.JSONField(blank=True, default=list)),
                ("default_filters", models.JSONField(blank=True, default=dict)),
                (
                    "default_sort",
                    models.CharField(
                        blank=True,
                        help_text='field code, optionally "-field" for descending.',
                        max_length=100,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("role", "Role"),
                            ("personal", "Personal"),
                        ],
                        default="system",
                        max_length=20,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="list_views",
                        to="platform_core.entitydefinition",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.role",
                    ),
                ),
            ],
            options={
                "db_table": "platform_list_view_definitions",
                "ordering": ["entity", "name"],
            },
        ),
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("file_format", models.CharField(default="xlsx", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to="platform_exports/",
                    ),
                ),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_jobs",
                        to="platform_core.entitydefinition",
                    ),
                ),
                (
                    "list_view",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="platform_core.listviewdefinition",
                    ),
                ),
            ],
            options={
                "db_table": "platform_export_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("record_number", models.CharField(blank=True, max_length=100)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Rendered from entity.title_template at save time.",
                        max_length=255,
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                ("parent_object_id", models.CharField(blank=True, max_length=64)),
                ("layout_version", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="platform_core.legalentity",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_custom_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="platform_core.lookupvalue",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="records",
                        to="platform_core.entitydefinition",
                    ),
                ),
            ],
            options={
                "db_table": "platform_custom_records",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["entity", "is_deleted"], name="pcr_entity_idx"
                    ),
                    models.Index(
                        fields=["parent_content_type", "parent_object_id"],
                        name="pcr_parent_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="fielddefinition",
            constraint=models.UniqueConstraint(
                fields=("entity", "code"), name="uniq_field_code_per_entity"
            ),
        ),
        migrations.AddIndex(
            model_name="attachmentvalue",
            index=models.Index(
                fields=["content_type", "object_id"], name="pav_object_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="fieldvalueuniqueness",
            constraint=models.UniqueConstraint(
                fields=("entity", "field", "scope_key", "value_hash"),
                name="uniq_field_value_per_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="formfieldplacement",
            constraint=models.UniqueConstraint(
                fields=("section", "field"), name="uniq_field_per_section"
            ),
        ),
    ]
