# Generated by Django 6.0.4 on 2026-10-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_core", "0004_customrecord_data_gin_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="legalentity",
            name="attributes",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
