# Generated by Django 4.2.16 on 2026-08-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="enabled_modules",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Subset of: announcements, recruitment, face_attendance, attendance, leave, payroll, expenses, separation, voice_commands, assessments",
            ),
        ),
    ]
