# Generated by Django 4.2.16 on 2026-08-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_platformadmin"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformadmin",
            name="failed_login_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="platformadmin",
            name="locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
