# Generated by Django 4.2.16 on 2026-08-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0004_platformadmin_failed_login_attempts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="custom_domain",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
