# Generated by Django 4.2.16 on 2026-08-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0005_client_custom_domain"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformSMTPSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host", models.CharField(blank=True, max_length=255)),
                ("port", models.PositiveIntegerField(default=587)),
                ("username", models.CharField(blank=True, max_length=255)),
                ("password", models.CharField(blank=True, max_length=255)),
                ("use_tls", models.BooleanField(default=True)),
                ("from_email", models.EmailField(blank=True, max_length=255)),
                (
                    "sender_name",
                    models.CharField(blank=True, default="Royal HRMS", max_length=255),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tenants_platform_smtp_settings",
            },
        ),
    ]
