# Generated by Django 4.2.16 on 2026-08-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0006_platformsmtpsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="pending_admin_password",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="client",
            name="provisioning_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("failed", "Failed"),
                ],
                default="active",
                max_length=10,
            ),
        ),
    ]
