# Generated by Django 4.2.16 on 2026-08-19 09:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0007_client_pending_admin_password_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformAdminPasswordResetToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("is_used", models.BooleanField(db_index=True, default=False)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reset_tokens",
                        to="tenants.platformadmin",
                    ),
                ),
            ],
            options={
                "db_table": "tenants_platform_admin_reset_token",
            },
        ),
        migrations.CreateModel(
            name="PlatformAdminAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="tenants.platformadmin",
                    ),
                ),
                (
                    "target_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_audit_logs",
                        to="tenants.client",
                    ),
                ),
            ],
            options={
                "db_table": "tenants_platform_admin_audit_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlatformAdminOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp", models.CharField(max_length=128)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("is_used", models.BooleanField(db_index=True, default=False)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otps",
                        to="tenants.platformadmin",
                    ),
                ),
            ],
            options={
                "db_table": "tenants_platform_admin_otp",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["admin", "is_used", "expires_at"],
                        name="tenants_pla_admin_i_e45db7_idx",
                    )
                ],
            },
        ),
    ]
