# Generated by Django 4.2.16 on 2026-08-19 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0008_platformadminpasswordresettoken_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="custom_domain",
        ),
    ]
