# Generated by Django 5.1.15 on 2026-08-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0009_remove_client_custom_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="contact_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="client",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="client",
            name="contract_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="expected_employee_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="plan",
            field=models.CharField(
                blank=True,
                choices=[
                    ("trial", "Trial"),
                    ("standard", "Standard"),
                    ("enterprise", "Enterprise"),
                ],
                max_length=20,
            ),
        ),
    ]
