# Generated by Django 5.1.15 on 2026-08-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0010_client_contact_name_client_contact_phone_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="plan",
        ),
        migrations.AddField(
            model_name="client",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="client",
            name="gstin",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
