// Single master list of countries for the whole app — every dropdown that
// needs "pick a country" (Nationality, Country of Origin, and any future
// field) reads from this one list instead of each component hand-typing
// its own. Based on the real ISO 3166-1 country list (the same reference
// used by immigration/banking systems), so it stays correct even decades
// from now: countries occasionally rename or split (Swaziland -> Eswatini
// in 2018, Burma -> Myanmar), and when that happens this is the one place
// to update — every screen using this list picks up the change immediately,
// instead of drifting out of sync the way separate hand-typed lists would.
//
// `name` is the country's name (for "Country of Origin"-style fields);
// `demonym` is the adjective form (for "Nationality"-style fields, e.g.
// "Indian" rather than "India"). India is listed first to match this app's
// existing convention (PhoneInput, LanguagesSelect) of defaulting to the
// most common case for this deployment rather than strict alphabetical
// order.
export interface CountryEntry {
  name: string;
  demonym: string;
}

export const COUNTRIES: CountryEntry[] = [
  { name: "India", demonym: "Indian" },
  { name: "Afghanistan", demonym: "Afghan" },
  { name: "Albania", demonym: "Albanian" },
  { name: "Algeria", demonym: "Algerian" },
  { name: "Andorra", demonym: "Andorran" },
  { name: "Angola", demonym: "Angolan" },
  { name: "Antigua and Barbuda", demonym: "Antiguan or Barbudan" },
  { name: "Argentina", demonym: "Argentine" },
  { name: "Armenia", demonym: "Armenian" },
  { name: "Australia", demonym: "Australian" },
  { name: "Austria", demonym: "Austrian" },
  { name: "Azerbaijan", demonym: "Azerbaijani" },
  { name: "Bahamas", demonym: "Bahamian" },
  { name: "Bahrain", demonym: "Bahraini" },
  { name: "Bangladesh", demonym: "Bangladeshi" },
  { name: "Barbados", demonym: "Barbadian" },
  { name: "Belarus", demonym: "Belarusian" },
  { name: "Belgium", demonym: "Belgian" },
  { name: "Belize", demonym: "Belizean" },
  { name: "Benin", demonym: "Beninese" },
  { name: "Bhutan", demonym: "Bhutanese" },
  { name: "Bolivia", demonym: "Bolivian" },
  { name: "Bosnia and Herzegovina", demonym: "Bosnian or Herzegovinian" },
  { name: "Botswana", demonym: "Motswana" },
  { name: "Brazil", demonym: "Brazilian" },
  { name: "Brunei", demonym: "Bruneian" },
  { name: "Bulgaria", demonym: "Bulgarian" },
  { name: "Burkina Faso", demonym: "Burkinabe" },
  { name: "Burundi", demonym: "Burundian" },
  { name: "Cabo Verde", demonym: "Cabo Verdean" },
  { name: "Cambodia", demonym: "Cambodian" },
  { name: "Cameroon", demonym: "Cameroonian" },
  { name: "Canada", demonym: "Canadian" },
  { name: "Central African Republic", demonym: "Central African" },
  { name: "Chad", demonym: "Chadian" },
  { name: "Chile", demonym: "Chilean" },
  { name: "China", demonym: "Chinese" },
  { name: "Colombia", demonym: "Colombian" },
  { name: "Comoros", demonym: "Comoran" },
  { name: "Congo (Republic of the)", demonym: "Congolese" },
  { name: "Congo (Democratic Republic of the)", demonym: "Congolese" },
  { name: "Costa Rica", demonym: "Costa Rican" },
  { name: "Croatia", demonym: "Croatian" },
  { name: "Cuba", demonym: "Cuban" },
  { name: "Cyprus", demonym: "Cypriot" },
  { name: "Czechia", demonym: "Czech" },
  { name: "Denmark", demonym: "Danish" },
  { name: "Djibouti", demonym: "Djiboutian" },
  { name: "Dominica", demonym: "Dominican" },
  { name: "Dominican Republic", demonym: "Dominican" },
  { name: "Ecuador", demonym: "Ecuadorian" },
  { name: "Egypt", demonym: "Egyptian" },
  { name: "El Salvador", demonym: "Salvadoran" },
  { name: "Equatorial Guinea", demonym: "Equatorial Guinean" },
  { name: "Eritrea", demonym: "Eritrean" },
  { name: "Estonia", demonym: "Estonian" },
  { name: "Eswatini", demonym: "Swazi" },
  { name: "Ethiopia", demonym: "Ethiopian" },
  { name: "Fiji", demonym: "Fijian" },
  { name: "Finland", demonym: "Finnish" },
  { name: "France", demonym: "French" },
  { name: "Gabon", demonym: "Gabonese" },
  { name: "Gambia", demonym: "Gambian" },
  { name: "Georgia", demonym: "Georgian" },
  { name: "Germany", demonym: "German" },
  { name: "Ghana", demonym: "Ghanaian" },
  { name: "Greece", demonym: "Greek" },
  { name: "Grenada", demonym: "Grenadian" },
  { name: "Guatemala", demonym: "Guatemalan" },
  { name: "Guinea", demonym: "Guinean" },
  { name: "Guinea-Bissau", demonym: "Bissau-Guinean" },
  { name: "Guyana", demonym: "Guyanese" },
  { name: "Haiti", demonym: "Haitian" },
  { name: "Honduras", demonym: "Honduran" },
  { name: "Hungary", demonym: "Hungarian" },
  { name: "Iceland", demonym: "Icelandic" },
  { name: "Indonesia", demonym: "Indonesian" },
  { name: "Iran", demonym: "Iranian" },
  { name: "Iraq", demonym: "Iraqi" },
  { name: "Ireland", demonym: "Irish" },
  { name: "Israel", demonym: "Israeli" },
  { name: "Italy", demonym: "Italian" },
  { name: "Jamaica", demonym: "Jamaican" },
  { name: "Japan", demonym: "Japanese" },
  { name: "Jordan", demonym: "Jordanian" },
  { name: "Kazakhstan", demonym: "Kazakhstani" },
  { name: "Kenya", demonym: "Kenyan" },
  { name: "Kiribati", demonym: "I-Kiribati" },
  { name: "Kosovo", demonym: "Kosovar" },
  { name: "Kuwait", demonym: "Kuwaiti" },
  { name: "Kyrgyzstan", demonym: "Kyrgyzstani" },
  { name: "Laos", demonym: "Lao" },
  { name: "Latvia", demonym: "Latvian" },
  { name: "Lebanon", demonym: "Lebanese" },
  { name: "Lesotho", demonym: "Basotho" },
  { name: "Liberia", demonym: "Liberian" },
  { name: "Libya", demonym: "Libyan" },
  { name: "Liechtenstein", demonym: "Liechtensteiner" },
  { name: "Lithuania", demonym: "Lithuanian" },
  { name: "Luxembourg", demonym: "Luxembourgish" },
  { name: "Madagascar", demonym: "Malagasy" },
  { name: "Malawi", demonym: "Malawian" },
  { name: "Malaysia", demonym: "Malaysian" },
  { name: "Maldives", demonym: "Maldivian" },
  { name: "Mali", demonym: "Malian" },
  { name: "Malta", demonym: "Maltese" },
  { name: "Marshall Islands", demonym: "Marshallese" },
  { name: "Mauritania", demonym: "Mauritanian" },
  { name: "Mauritius", demonym: "Mauritian" },
  { name: "Mexico", demonym: "Mexican" },
  { name: "Micronesia", demonym: "Micronesian" },
  { name: "Moldova", demonym: "Moldovan" },
  { name: "Monaco", demonym: "Monegasque" },
  { name: "Mongolia", demonym: "Mongolian" },
  { name: "Montenegro", demonym: "Montenegrin" },
  { name: "Morocco", demonym: "Moroccan" },
  { name: "Mozambique", demonym: "Mozambican" },
  { name: "Myanmar", demonym: "Burmese" },
  { name: "Namibia", demonym: "Namibian" },
  { name: "Nauru", demonym: "Nauruan" },
  { name: "Nepal", demonym: "Nepali" },
  { name: "Netherlands", demonym: "Dutch" },
  { name: "New Zealand", demonym: "New Zealander" },
  { name: "Nicaragua", demonym: "Nicaraguan" },
  { name: "Niger", demonym: "Nigerien" },
  { name: "Nigeria", demonym: "Nigerian" },
  { name: "North Korea", demonym: "North Korean" },
  { name: "North Macedonia", demonym: "Macedonian" },
  { name: "Norway", demonym: "Norwegian" },
  { name: "Oman", demonym: "Omani" },
  { name: "Pakistan", demonym: "Pakistani" },
  { name: "Palau", demonym: "Palauan" },
  { name: "Palestine", demonym: "Palestinian" },
  { name: "Panama", demonym: "Panamanian" },
  { name: "Papua New Guinea", demonym: "Papua New Guinean" },
  { name: "Paraguay", demonym: "Paraguayan" },
  { name: "Peru", demonym: "Peruvian" },
  { name: "Philippines", demonym: "Filipino" },
  { name: "Poland", demonym: "Polish" },
  { name: "Portugal", demonym: "Portuguese" },
  { name: "Qatar", demonym: "Qatari" },
  { name: "Romania", demonym: "Romanian" },
  { name: "Russia", demonym: "Russian" },
  { name: "Rwanda", demonym: "Rwandan" },
  { name: "Saint Kitts and Nevis", demonym: "Kittitian or Nevisian" },
  { name: "Saint Lucia", demonym: "Saint Lucian" },
  { name: "Saint Vincent and the Grenadines", demonym: "Vincentian" },
  { name: "Samoa", demonym: "Samoan" },
  { name: "San Marino", demonym: "Sammarinese" },
  { name: "Sao Tome and Principe", demonym: "Sao Tomean" },
  { name: "Saudi Arabia", demonym: "Saudi" },
  { name: "Senegal", demonym: "Senegalese" },
  { name: "Serbia", demonym: "Serbian" },
  { name: "Seychelles", demonym: "Seychellois" },
  { name: "Sierra Leone", demonym: "Sierra Leonean" },
  { name: "Singapore", demonym: "Singaporean" },
  { name: "Slovakia", demonym: "Slovak" },
  { name: "Slovenia", demonym: "Slovenian" },
  { name: "Solomon Islands", demonym: "Solomon Islander" },
  { name: "Somalia", demonym: "Somali" },
  { name: "South Africa", demonym: "South African" },
  { name: "South Korea", demonym: "South Korean" },
  { name: "South Sudan", demonym: "South Sudanese" },
  { name: "Spain", demonym: "Spanish" },
  { name: "Sri Lanka", demonym: "Sri Lankan" },
  { name: "Sudan", demonym: "Sudanese" },
  { name: "Suriname", demonym: "Surinamese" },
  { name: "Sweden", demonym: "Swedish" },
  { name: "Switzerland", demonym: "Swiss" },
  { name: "Syria", demonym: "Syrian" },
  { name: "Taiwan", demonym: "Taiwanese" },
  { name: "Tajikistan", demonym: "Tajikistani" },
  { name: "Tanzania", demonym: "Tanzanian" },
  { name: "Thailand", demonym: "Thai" },
  { name: "Timor-Leste", demonym: "Timorese" },
  { name: "Togo", demonym: "Togolese" },
  { name: "Tonga", demonym: "Tongan" },
  { name: "Trinidad and Tobago", demonym: "Trinidadian or Tobagonian" },
  { name: "Tunisia", demonym: "Tunisian" },
  { name: "Turkey", demonym: "Turkish" },
  { name: "Turkmenistan", demonym: "Turkmen" },
  { name: "Tuvalu", demonym: "Tuvaluan" },
  { name: "Uganda", demonym: "Ugandan" },
  { name: "Ukraine", demonym: "Ukrainian" },
  { name: "United Arab Emirates", demonym: "Emirati" },
  { name: "United Kingdom", demonym: "British" },
  { name: "United States", demonym: "American" },
  { name: "Uruguay", demonym: "Uruguayan" },
  { name: "Uzbekistan", demonym: "Uzbekistani" },
  { name: "Vanuatu", demonym: "Ni-Vanuatu" },
  { name: "Vatican City", demonym: "Vatican" },
  { name: "Venezuela", demonym: "Venezuelan" },
  { name: "Vietnam", demonym: "Vietnamese" },
  { name: "Yemen", demonym: "Yemeni" },
  { name: "Zambia", demonym: "Zambian" },
  { name: "Zimbabwe", demonym: "Zimbabwean" },
];
