# Generated by Django 6.0.4 on 2026-09-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0002_seed_performance_manage_cycles_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="evidence_reference",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="goal",
            name="outcome_measure",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="goal",
            name="self_comments",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="goal",
            name="self_rating",
            field=models.CharField(
                blank=True,
                choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4"), ("5", "5")],
                default="",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="goal",
            name="weight_percent",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="performancereview",
            name="acknowledged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="performancereview",
            name="hr_calibrated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="performancereview",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="performancereview",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("self_review", "Awaiting Manager Review"),
                    ("hr_calibration", "Awaiting HR Calibration"),
                    ("published", "Published"),
                    ("completed", "Completed"),
                ],
                db_index=True,
                default="not_started",
                max_length=20,
            ),
        ),
    ]
